ros2/ros2cli

ros2cli/ros2cli/daemon/__init__.py
ros2cli/ros2cli/node/direct.py

I needed this to distinguish between the daemon and the ros2 tool when debugging with `ros2 node list -a`.
Also, this will be good to have as an option when/if node names become unique.

add suffix to node name in daemon

---

ros2cli/ros2cli/daemon/__init__.py
ros2cli/ros2cli/node/daemon.py

Addresses #6.
The daemon will only answer requests for matching RMW impl. Others are ignored and the client falls back to a direct node.
The second commit also prevents access to the daemon from non-localhost. I just think that is a more conservative default for now...

update daemon to only handle local requests for matching rmw impl

---

ros2run/ros2run/api/__init__.py

The first commit removes the unused `node` argument from the signatures.
The second commit considers `PATHEXT` on Windows to allow calling e.g. `ros2 run demo_nodes_py talker` (rather than needing to type `ros2 run demo_nodes_py talker.exe`).

Improve executable selection

---

ros2service/package.xml
ros2service/ros2service/verb/call.py
ros2topic/ros2topic/verb/pub.py

This should be backwards compatible with the JSON style inputs. Also, these packages already needed yaml, so it's not a new dependency. It also makes using this feature on Windows easier since you don't have to so quote escaping in a lot of cases.
@Kukanani FYI you should be able to do `ros2 topic pub /chatter std_msgs/String "data: Hello world"` with this pr.

use yaml for parsing msg and srv values

---

ros2cli/completion/ros2-argcomplete.bash

Check for Python 3 variation of bash function first.
Fixes #25.
Ready for review.

support python3-argcomplete

---

ros2topic/ros2topic/verb/pub.py

Follow up of #24.
This handles `ValueErrors` as well. To reproduce try:
```
ros2 topic pub initialpose geometry_msgs/PoseWithCovarianceStamped "header:
stamp:
sec: 'sec'
nanosec: 0.5
frame_id: 'map'   
pose:
pose:
position: {x: 5.5, y: 4.5, z: 0.0}
orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
covariance: [0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0,    0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
0.0, 0.0, 0.0, 0.0, 0.0, 0.0]"
```

also handle ValueError nicely

---

ros2pkg/ros2pkg/api/__init__.py
ros2pkg/ros2pkg/verb/executables.py
ros2pkg/setup.py
ros2run/ros2run/api/__init__.py
ros2run/ros2run/command/run.py

Fixes #21.
I ran the nosetests locally rather than triggering full CI builds.
Ready for review.

add ros2 pkg executables

---

ros2cli/ros2cli/cli.py

E.g. for `ros2 run pkgname <tab>` this will ensure that only executable names will show up. For other commands / verbs that will still show other options. `run` just doesn't have any other ones beside `-h` and `--help`.

hide help options from completion

---

ros2cli/package.xml

the rosdep key has been added in https://github.com/ros/rosdistro/pull/15406

add exec_depend on python3-pkg-resources

---

ros2cli/ros2cli/daemon/__init__.py
ros2cli/ros2cli/node/daemon.py

The first commit fixes #10.
The second commit makes sure that the folder which the daemon was launched from can be deleted even while the daemon is still running.

Improve windows daemon

---

ros2run/ros2run/api/__init__.py
ros2run/ros2run/command/run.py

According to the proposal by @wjwwood on my [question](http://answers.ros.org/question/267261/how-can-i-run-ros2-nodes-in-a-debugger-eg-gdb/), I am providing a pull request to add the '--prefix' argument from 'rosrun' to 'ros2 run'.

added --prefix argument to ros2 run

---

ros2run/ros2run/command/run.py

Only "works" once kislyuk/argcomplete#224 becomes available.
Otherwise the code will gracefully fall back and keep the behavior as-is.

run: suppress prefix completion

---

ros2cli/ros2cli/command/__init__.py
ros2cli/ros2cli/node/daemon.py
ros2cli/ros2cli/plugin_system.py
ros2msg/test/test_cli.py
ros2run/ros2run/command/run.py
ros2srv/test/test_cli.py
ros2topic/ros2topic/verb/echo.py

update style to satisfy new flake8 plugins

---

ros2topic/ros2topic/verb/pub.py

Instead of showing a stacktrace with the following exception:
```
AttributeError: 'str' object has no attribute 'items'
```
this patch prints an error message ~~which includes an example value for the specified message type~~.

better error message when passing an invalid value to ros2 topic pub

---

ros2cli/ros2cli/verb/daemon/stop.py

Instead of showing a stacktrace with the following exception:
```
AttributeError: 'Node' object has no attribute 'system'
```
this patch prints an error message describing why it failed.

add error message when trying to stop a daemon using a different rmw implementation

---

ros2run/ros2run/api/__init__.py

Without this patch when running an executable using `ros2 run` and hitting `Ctrl-C` / sending a `SIGINT` the `ros2cli` Python script would raise a `KeyboardInterrupt` in the line invoking `subprocess.run(...)`. This immediately stop any further processing. This can be seen easily when running `ros2 run demo_nodes_cpp allocator_tutorial` and pressing `Ctrl-C`. Depending on the timing you might not see any statistic output, maybe some of it, or the complete statistic.
This patch wraps the subprocess invocation in a loop and continue on `KeyboardInterrupt`. The process should exit on its own since it is also receiving the `SIGINT`. If not the user can always kill the process explicitly (e.g. using `Ctrl-\`).
This is very similar to ros2/launch#58.

fix SIGINT handling in ros2 run

---

ros2topic/ros2topic/verb/echo.py

If the user passes "/topic_name" to the ros2 echo
command, it works properly.  If they pass "topic_name"
to the ros2 echo command, it fails to match.  This
change just allows us to deal with non-absolute topic
names.
This should fix #54 .  I ran the tests against the ros2cli package locally,
with no errors.  No CI since this is python code and it won't tell us very much.
Signed-off-by: Chris Lalancette <clalancette@gmail.com>

Support non-absolute topic names.

---

ros2topic/ros2topic/verb/echo.py

We need to catch ValueErrors when actually doing the expansion,
then InvalidTopicNameException when doing the validation.

Make sure to check errors when expanding the topic name.

---

ros2run/ros2run/command/run.py

This pull request try to improve on #40.
The use of narg=REMAINDER in [argparse](https://docs.python.org/3.5/library/argparse.html#nargs) exhibit the wanted behavior where every parameters after the node name are passed to the node without the need of the -- separator.
The prefix parameter (--prefix) still need to be placed before package and node to not be passed to the node. May be it is useful to print a warning if the prefix is had at the end of the command line ?
Let me know if i have missed something here.

Improve parameters passing to node in ros2run

---

ros2service/ros2service/verb/call.py
ros2topic/ros2topic/verb/pub.py

I kept the default behavior (publishing every second) the same for now as we dont have latching.
Not sure what the right place is to put the `float_or_int` utility for reuse. I'm not convinced it belongs in the Base class but I can imagine it being reused in many places. Maybe a set of argparse utilities in ros2cli would make sense. 
@dirk-thomas thoughts?

[ros2topic] pub: add --repeat

---

ros2cli/ros2cli/daemon/__init__.py
ros2cli/ros2cli/node/daemon.py

new version of flake8 complains as xmlrpc is considered a system header and thus needs to be imported in the previous block.
cc @wjwwood as build cop

fix import order

---

ros2cli/ros2cli/cli.py
ros2cli/ros2cli/command/__init__.py
ros2cli/ros2cli/command/daemon.py
ros2msg/ros2msg/command/msg.py
ros2node/ros2node/command/node.py
ros2pkg/ros2pkg/command/pkg.py
ros2service/ros2service/command/service.py
ros2srv/ros2srv/command/srv.py
ros2topic/ros2topic/command/topic.py

When no `command` / `verb` is passed the full help is printed as if the user would have passed `--help`.
Fixes #74.
The API is backward compatible so that the behavior of existing extensions isn't changes. Extensions implemented in other repositories could be updated in the same way (not to require the `verb`) if they want to show the full help text in that case.

print full help when no command is passed

---

ros2cli/ros2cli/daemon/__init__.py
ros2cli/ros2cli/node/daemon.py

Removes the rmw impl. specific path from the daemon URL. This allows a client with any rmw impl. to talk to a daemon with any rmw impl.
Fixes #69.

use rmw agnostic daemon URL

---

ros2topic/ros2topic/verb/pub.py

I needed this for testing and figured I'll just submit it. Ideally we would do the same for `echo` but as it uses [DirectNode](https://github.com/ros2/ros2cli/blob/6b18ca7814a14d3e9b949523ccaf1e44a592fe8d/ros2topic/ros2topic/verb/echo.py#L79) and create nodes based on process ID that will be a bit more intricated so I settled on this incremental PR for now.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4029)](http://ci.ros2.org/job/ci_linux/4029/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1121)](http://ci.ros2.org/job/ci_linux-aarch64/1121/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3359)](http://ci.ros2.org/job/ci_osx/3359/)
* Windows [![Build …

[ros2 topic pub] allow to pass a node name to ros2 topic pub

---

ros2service/ros2service/verb/call.py

This updates to use the new client api.
connects to ros2/rclpy#170

`ros2 service` Use new client api

---

ros2cli/resource/local_setup.bash
ros2cli/resource/local_setup.zsh
ros2cli/setup.py

Fixes ros2/ros2cli#78. Connect to ros2/ros2cli#78.
I have applied the same changes to the installed location in `/opt/ros/ardent` which made it work for me from Debian packages when sourcing `/opt/ros/ardent/local_setup.bash`.

source bash completion script from setup file

---

ros2pkg/ros2pkg/verb/create.py

`flake8-builtins` >=1.2 will report this now

Avoid use of license as variable name

---

ros2param/package.xml
ros2param/ros2param/api/__init__.py
ros2param/ros2param/command/param.py
ros2param/ros2param/verb/__init__.py
ros2param/ros2param/verb/delete.py
ros2param/ros2param/verb/get.py
ros2param/ros2param/verb/list.py
ros2param/ros2param/verb/set.py
ros2param/setup.py
ros2param/test/test_copyright.py
ros2param/test/test_flake8.py
ros2param/test/test_pep257.py

* `list` outputs the names of all parameters, either for all nodes or a node passed as an argument
* `get` outputs the value of a specific parameter, the type information can be suppressed
* `set` sets a parameter, the type is being determined by guessing the primitive types, no array types atm
* `delete` removed a specific parameter (at least it should but it seems that the service doesn't work for that use case).

add ros2 param

---

ros2lifecycle/package.xml
ros2lifecycle/ros2lifecycle/api/__init__.py
ros2lifecycle/ros2lifecycle/command/lifecycle.py
ros2lifecycle/ros2lifecycle/verb/__init__.py
ros2lifecycle/ros2lifecycle/verb/get.py
ros2lifecycle/ros2lifecycle/verb/list.py
ros2lifecycle/ros2lifecycle/verb/set.py
ros2lifecycle/setup.py
ros2lifecycle/test/test_copyright.py
ros2lifecycle/test/test_flake8.py
ros2lifecycle/test/test_pep257.py

Adding `ros2 lifecycle` with the following verbs: `get`, `list`, `set`.
Requires ros2/rosidl#281.

add ros2 lifecycle

---

ros2param/ros2param/verb/list.py

Not showing the node name when a specific node was requested.
Follow up of #95.

update ros2 param list output for a specific node

---

ros2service/ros2service/verb/list.py

While `args.include_hidden_services` was already passed to `get_service_names_and_types` there was no such argument.

add missing arg to ros2 service list

---

ros2cli/completion/ros2-argcomplete.zsh

Without this sourcing the `zsh` file results in:
```command not found: complete```

use (bash)compinit for zsh completion

---

ros2param/ros2param/verb/get.py

Without:
```
$ ros2 param get parameter_node garbage_param
Unknown parameter type '0'
```
With:
```
$ ros2 param get parameter_node garbage_param
Parameter not set.
```

Specific message when unset parameters are retrieved

---

ros2cli/ros2cli/node/direct.py

@dirk-thomas Is this timer intended to stay alive and be used by consumers?
Otherwise I can update this PR to destroy the timer before exiting the init function

cancel timer before letting caller use the node to avoid spurious wakeups for consumers

---

ros2topic/ros2topic/verb/echo.py

Opening for visibility until a better workaround is found
Right now the spinning in DIrectNode causes #112 on Connext.
This PR hackily moves the logic to create and destroy the node in the echo verb itself as there is no need for a bootstrap phase for the node as it doesn't need to aggregate network information.
Fixes #112

pass actual node object to subscriber function

---

ros2msg/package.xml
ros2msg/test/test_api.py
ros2pkg/test/test_api.py
ros2pkg/test/test_cli.py
ros2srv/package.xml
ros2srv/test/test_api.py

Before: [![Build Status](http://build.ros2.org/buildStatus/icon?job=Bdev__ros2cli__ubuntu_bionic_amd64&build=1)](http://build.ros2.org/job/Bdev__ros2cli__ubuntu_bionic_amd64/1/)
After: [![Build Status](http://build.ros2.org/buildStatus/icon?job=Bdev__ros2cli__ubuntu_bionic_amd64&build=2)](http://build.ros2.org/job/Bdev__ros2cli__ubuntu_bionic_amd64/2/)

fix tests to use packages which register themselves at the index

---

ros2cli/ros2cli/daemon/__init__.py
ros2cli/ros2cli/node/daemon.py

Potential fix for #120 
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4848)](http://ci.ros2.org/job/ci_linux/4848/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1701)](http://ci.ros2.org/job/ci_linux-aarch64/1701/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4026)](http://ci.ros2.org/job/ci_osx/4026/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4892)](http://ci.ros2.org/job/ci_windows/4892/)
without the patch:
```bash
Traceback (most recent call last):
File "/opt/ros/bouncy/bin/ros2", line 11, in <module>
load_entry_point('ros2cli==0.5.2', 'console_scripts', 'ros2')()
File "/opt/ros/bouncy/lib/python3.6/site-packages/ros2cli/cli.py", …
```

Check rmw identifier

---

ros2topic/ros2topic/verb/pub.py

I found myself patching the code several times when I wanted to publish messages with a higher rate but without the overhead of flooding the console (which essentially slows down the loop). Hence the first commit adds an option to control how many published message should be printed (e.g. try `-r 1000 -p 250`).
The second commit only removes a default value which doesn't make sense. The default node name is not as indicated and empty string but is being set by the script later if no not-empty node name is provided.

 [topic pub] add option to limit printing published msgs

---

ros2topic/ros2topic/verb/echo.py

Issue1: ros2 topic echo pointcould2(big arrays), has no response, updated the logical to make more sensible.
a. (by default) full_length=false, truncate_length=128, then print max 128 (fix big arrays issue)
b. pass truncate_length=X, then print max X.
c. pass full_length=true (whatever truncate_length), then set truncate_length=None and print full_length.
Issue2: pass truncate_length to _convert_value(), this should be required.
Signed-off-by: Chris Ye <chris.ye@intel.com>
connect to ros2/ros2cli#127

Fix echo for big array messages

---

ros2topic/package.xml

this package uses `rclpy`  to publish and subscribe

[ros2topic] add missing rclpy dependency

---

ros2topic/ros2topic/verb/echo.py
ros2topic/test/test_echo.py

Fixes bug introduced by #135 
https://github.com/ros2/ros2cli/pull/135#discussion_r210660143
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5057)](http://ci.ros2.org/job/ci_linux/5057/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1853)](http://ci.ros2.org/job/ci_linux-aarch64/1853/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4199)](http://ci.ros2.org/job/ci_osx/4199/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5051)](http://ci.ros2.org/job/ci_windows/5051/)

Don't truncate dictionary keys

---

ros2topic/ros2topic/verb/pub.py

when rate is 1000, time.sleep() in main loop will cost about 150ms every 1s, use time comparison instead of time.sleep(), save sleep cycle time lossing
Signed-off-by: Chris Ye <chris.ye@intel.com>

[ros2topic] fix pub rate reduced issue

---

ros2cli/ros2cli/daemon/__init__.py
ros2node/ros2node/api/__init__.py
ros2node/ros2node/verb/list.py
ros2param/ros2param/api/__init__.py
ros2param/ros2param/verb/delete.py
ros2param/ros2param/verb/get.py
ros2param/ros2param/verb/list.py
ros2param/ros2param/verb/set.py

Follow up of ros2/rmw#142.
Proposed to replace #143 and #144.
Fixes #105, fixes #128 and fixes ros2/ros2#569.

node name with namespace

---

ros2lifecycle/ros2lifecycle/api/__init__.py
ros2lifecycle/ros2lifecycle/verb/get.py
ros2lifecycle/ros2lifecycle/verb/list.py
ros2lifecycle/ros2lifecycle/verb/set.py

I think the `ros2lifecycle` is currently not working currently since https://github.com/ros2/ros2cli/pull/146 got merged.

comply with new node representation

---

ros2topic/package.xml
ros2topic/ros2topic/api/__init__.py
ros2topic/ros2topic/verb/delay.py
ros2topic/ros2topic/verb/hz.py
ros2topic/setup.py

For performance test to print the average publishing rate to screen. Ported rostopic hz command from ros to ros2, based on the file as below
https://github.com/ros/ros_comm/blob/melodic-devel/tools/rostopic/src/rostopic/__init__.py
Signed-off-by: Chris Ye <chris.ye@intel.com>
Connects to https://github.com/ros2/ros2cli/issues/132

Enable ros2tpoic hz command

---

ros2msg/ros2msg/api/__init__.py
ros2srv/ros2srv/api/__init__.py

ros2/rosidl#308 added the folder a message or service lives in to the ament resource named to `rosidl_interfaces`. This broke tests for ros2msg and ros2srv. This PR fixes those tests by stripping the folder from the interface names.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=5422)](http://ci.ros2.org/job/ci_linux/5422/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=2129)](http://ci.ros2.org/job/ci_linux-aarch64/2129/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=4496)](http://ci.ros2.org/job/ci_osx/4496/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=5363)](http://ci.ros2.org/job/ci_windows/5363/)

Ignore folder in rosidl_interfaces to fix CI

---

ros2msg/ros2msg/api/__init__.py
ros2srv/ros2srv/api/__init__.py

Handle `.idl` files generated by ros2/rosidl#331 properly.

handle idl files correctly

---

ros2service/ros2service/verb/list.py

The `ros2 service` command and `ros2 service list` command both had `--include-hidden-services` arguments. Because of the latter the first argument did nothing. This makes listing hidden services the same as listing hidden topics
Before
``` bash
ros2 service --include-hidden-services list
ros2 service list --include-hidden-services
```
With this PR
```bash
ros2 service --include-hidden-services list
ros2 topic --include-hidden-topics list
```

Make listing hidden services symmetric with topics

---

ros2service/ros2service/verb/call.py

Like 417d46f3a5caf2458e6eadeb52d2ae435782bcf1 but for services. This imports the service type from `.action` if the service name indicates it's an action service.
To manually test:
1. Checkout  https://github.com/ros2/examples/pull/220
1. run the server
```
ros2 run examples_rclcpp_minimal_action_server action_server_not_composable
```
1. try to call the send goal service
```
ros2 service call /fibonacci/_action/send_goal example_interfaces/Fibonacci_Goal
```
1. try to call the get result service
```
ros2 service call /fibonacci/_action/get_result example_interfaces/Fibonacci_Result
```

Check in action module if action service

---

ros2topic/ros2topic/api/__init__.py
ros2topic/ros2topic/verb/delay.py
ros2topic/ros2topic/verb/echo.py
ros2topic/ros2topic/verb/hz.py
ros2topic/ros2topic/verb/pub.py

The first commit fixes a bug where the option `--include-hidden-topics` wasn't being passed to the call to `get_topic_names_and_types()` or `get_msg_class()`. This prevented `ros2 topic echo/delay/hz` from working with hidden topics. I looked at adding a test, but it's non-trivial. Instead here are manual tests.
Publish on a hidden topic
```
ros2 topic pub /fibonacci/_action/status action_msgs/GoalStatusArray
```
Try to do these
```
ros2 topic --include-hidden-topics echo /fibonacci/_action/status
ros2 topic --include-hidden-topics delay /fibonacci/_action/status
ros2 topic --include-hidden-topics hz /fibonacci/_action/status
```
The second commit allows import action types which come from the module `.action` instead of `.msg`.
Publish on a hidden topic with a generated action message. …

Fix ros2 topic echo, delay, hz with hidden topics + fix for action feedback topic

---

ros2node/ros2node/api/__init__.py
ros2node/ros2node/verb/info.py
ros2node/setup.py

*Summary:* Provide the info verb under the node command
`ros2 node info /minimal_publisher`
Example:
```
/minimal_publisher
Subscribers:
/parameter_events: rcl_interfaces/ParameterEvent
Publishers:
/parameter_events: rcl_interfaces/ParameterEvent
/topic: std_msgs/String
Services:
/minimal_publisher/describe_parameters: rcl_interfaces/DescribeParameters
/minimal_publisher/get_parameter_types: rcl_interfaces/GetParameterTypes
/minimal_publisher/get_parameters: rcl_interfaces/GetParameters
/minimal_publisher/list_parameters: rcl_interfaces/ListParameters
/minimal_publisher/set_parameters: rcl_interfaces/SetParameters
/minimal_publisher/set_parameters_atomically: rcl_interfaces/SetParametersAtomically
```
Connects to ros2/rcl#333

Add ros2 node info verb

---

ros2lifecycle/ros2lifecycle/verb/get.py

fixes ros2/ros2cli#170
has to be rebased when ros2/ros2cli#167 is merged.
This PR basically removed the obsolete argument `--transitions` for the `ros2 lifecycle get` command. The transitions can be displayed by invoking `ros2 lifecycle list [-a] <node_name>`

Remove unused cli option

---

ros2node/ros2node/verb/info.py

This description is reflected in the output of `ros2 node info -h`.

Fix node info verb description

---

ros2cli/ros2cli/node/__init__.py
ros2cli/ros2cli/node/direct.py
ros2node/ros2node/api/__init__.py
ros2service/ros2service/verb/call.py
ros2topic/ros2topic/verb/pub.py

This is part of the improvements suggested [here](https://discourse.ros.org/t/ros2-security-cli-tools/6647/) mainly intended for CLI tools' usability with security.
* All ros2cli nodes will start with prefix `ros2cli_node`. 
* https://github.com/ros2/rcl/pull/332
* https://github.com/ros2/rosbag2/pull/60
https://discourse.ros.org/t/ros2-security-cli-tools/6647/
https://github.com/ros2/sros2/issues/69

Consistent node naming

---

ros2topic/ros2topic/verb/echo.py

Failures in [nightly_linux-aarch64_debug #713](https://ci.ros2.org/job/nightly_linux-aarch64_debug/713), [nightly_linux-aarch64_extra_rmw_release #245](https://ci.ros2.org/job/nightly_linux-aarch64_extra_rmw_release/245), [nightly_linux-aarch64_release #673](https://ci.ros2.org/job/nightly_linux-aarch64_release/673), [nightly_linux_debug #1088](https://ci.ros2.org/job/nightly_linux_debug/1088), [nightly_linux_extra_rmw_release #241](https://ci.ros2.org/job/nightly_linux_extra_rmw_release/241), [nightly_linux_release #1069](https://ci.ros2.org/job/nightly_linux_release/1069), [nightly_osx_debug #1143](https://ci.ros2.org/job/nightly_osx_debug/1143), [nightly_osx_extra_rmw_release #279](https://ci.ros2.org/job/nightly_osx_extra_rmw_release/279), [nightly_osx_release …

Fix flake8 error due to overindentation

---

ros2pkg/ros2pkg/resource/ament_cmake/CMakeLists.txt.em

Imo all linters should be enabled by default with the comment being available how to skip them. Otherwise the high probability is that they won't we used by users which just expand the template but don't edit the file.

use all linters by default

---

ros2cli/ros2cli/entry_points.py
ros2cli/ros2cli/plugin_system.py

Use [non-deprecated method](https://docs.python.org/3.7/library/logging.html#logging.Logger.warning).
[![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6367)](https://ci.ros2.org/job/ci_linux/6367/)

update logger.warn (deprecated) to logger.warning

---

ros2node/ros2node/api/__init__.py
ros2node/ros2node/verb/info.py
ros2node/test/test_node.py

Fixes #201 
Fixes #181 
Initial '/' was missing when the node was inside a namespace.
Now, non fully qualified names are also accepted.
Added unit test.

Solved bug when trying to find node info in namespaces

---

CONTRIBUTING.md

The patch proposes an addition to the `CONTRIBUTING.md` file mentioning the requirement to sign-off commits as a way to certify the origin.
Please provide feedback in the form of proposed changes if you think the wording should be changed.
Once this PR has been accepted I will apply the same change to all other repositories which will be subject to the DCO.

add section about DCO to CONTRIBUTING.md

---

ros2component/ros2component/api/__init__.py
ros2component/ros2component/verb/load.py

`namespace_name` should be `node_namespace` as it is in the service call (https://github.com/ros2/rcl_interfaces/blob/1189517a0217a2cb9f78e71c2959542429ad9fc0/composition_interfaces/srv/LoadNode.srv#L9)

Fix component arguments to be inline with service.

---

ros2param/ros2param/api/__init__.py
ros2param/test/test_api.py

Using YAML parsing to determine the value parameter type, the supported parameter types are extended to array types. Only the byte array type is excluded, I don't see a way of expressing that in YAML in an unambiguous way.
Fixes #198

Add capability to use ros2 param set for array types

---

ros2component/package.xml
ros2component/ros2component/api/__init__.py
ros2component/ros2component/verb/list.py
ros2component/ros2component/verb/load.py
ros2component/ros2component/verb/standalone.py
ros2component/ros2component/verb/unload.py
ros2component/setup.py

Fixes #225. This pull request adds a `run` verb to start a component on a standalone container, for instance:
```sh
ros2 component run composition composition::Talker -n my_talker
```
But it also:
- Adds `--quiet` flag to existing verbs to ease shell scripting.
- Adds missing dependencies to the `package.xml`
- Mildly refactors the internal package API

Improve ros2 component CLI

---

ros2component/ros2component/verb/standalone.py

Before this PR:
```
$ ros2 component -h
Failed to load entry point 'standalone': module 'ros2component.verb.standalone' has no attribute 'StandaloneVerb'
usage: ros2 component [-h]
Call `ros2 component <command> -h` for more detailed
usage. ...
Various component related sub-commands
optional arguments:
-h, --help            show this help message and exit
Commands:
list    Output a list of running containers and components
load    Load a component into a container node
types   Output a list of components registered in the ament index
unload  Unload a component from a container node
```
With this PR:
```
$ ros2 component -h
usage: ros2 component [-h]
Call `ros2 component <command> -h` for more detailed
usage. ...
Various component related sub-commands
optional arguments:
-h, --help …
```

fix name of standalone verb

---

ros2action/package.xml
ros2action/test/test_xmllint.py
ros2cli/package.xml
ros2cli/test/test_xmllint.py
ros2component/package.xml
ros2component/test/test_xmllint.py
ros2lifecycle/package.xml
ros2lifecycle/test/test_xmllint.py
ros2msg/package.xml
ros2msg/test/test_xmllint.py
ros2multicast/package.xml
ros2multicast/test/test_xmllint.py
ros2node/package.xml
ros2node/test/test_xmllint.py
ros2param/package.xml
ros2param/test/test_xmllint.py
ros2pkg/package.xml
ros2pkg/test/test_xmllint.py
ros2run/package.xml
ros2run/test/test_xmllint.py
ros2service/package.xml
ros2service/test/test_xmllint.py
ros2srv/package.xml
ros2srv/test/test_xmllint.py
ros2topic/package.xml
ros2topic/test/test_xmllint.py

Similar to https://github.com/ros2/rosidl_python/pull/53.
Maybe there is a better way of doing this? is there something like `ament_lint_common` for python packages?

add xmllint linter test

---

ros2topic/ros2topic/verb/echo.py

Related to ros2/ros2cli#154.
Instead of an empty line use `---` to separate the yaml output of messages.
It allows to copy-n-paste multiple messages and load them via `yaml.load_all()`.

separate the yaml of messages with three dashes

---

ros2topic/ros2topic/api/__init__.py

Fixes #235.
Now the 'bw', 'hz', and 'delay' verbs work again.

[ros2topic] Handle multiple namespace parts in message type

---

ros2lifecycle/ros2lifecycle/api/__init__.py

The current ros2lifecycle command line tools are broken, because the type identification for the service to lifecycle nodes are inaccurate. 
The new type for the service has to be specified with `lifecycle_msgs/srv/GetState`.
Signed-off-by: Karsten Knese <karsten@openrobotics.org>

use new type identification for lifecycle nodes

---

ros2service/ros2service/verb/call.py

Similar problem as described here: https://github.com/ros2/ros2cli/pull/241
`ros2 service call ...` fails because the new service types are parsed incorrectly.
Signed-off-by: Karsten Knese <karsten@openrobotics.org>

use new type identification for service calls

---

ros2cli/resource/local_setup.zsh

This only affects the Debian package - not a from source build with `colcon`.

fix sourcing argcomplete script in zsh

---

ros2topic/ros2topic/verb/pub.py

fixes https://github.com/ros2/ros2cli/issues/244
I am not sure whether this is the right default value, but given the name, it sounds sensible to me.
If the idea is to necessarily expose a QoS profile, I think we should change the command line to force a qos profile and not being optional.
Signed-off-by: Karsten Knese <karsten@openrobotics.org>

use system_default as qos for ros2 topic pub

---

ros2service/ros2service/verb/call.py

Keeps legacy support to improve behavior reported in ros2/demos#344.

add support for service type name without 'srv' namespace part

---

ros2topic/ros2topic/verb/bw.py
ros2topic/ros2topic/verb/delay.py
ros2topic/ros2topic/verb/hz.py

only allow window sizes of 1 and higher

---

ros2action/ros2action/verb/send_goal.py

 reset goal_handle to avoid attempt to cancel

---

ros2lifecycle/ros2lifecycle/verb/get.py

Previously, the 'get' verb was returning the state for all lifecycle nodes.
Fixes #233

[ros2lifecycle] Only return the state for the node requested

---

ros2component/ros2component/verb/standalone.py

This prevents zombie container processes from hanging around when a
component fails to load.
Closes: #260

[ros2component] Stop the standalone container when load fails

---

ros2topic/ros2topic/verb/type.py
ros2topic/setup.py

Add the `type` verb which return the type of a given topic.
E.g.
```
$ ros2 topic type /rosout
rcl_interfaces/msg/Log
```

add 'topic type' verb

---

ros2topic/ros2topic/verb/find.py
ros2topic/setup.py

Add the `find` verb which lists all topics of a given type.
E.g.  
```terminal
$ ros2 topic find rcl_interfaces/msg/Log
/rosout
```
or with `count-topics` option,  
```terminal
$ ros2 topic find rcl_interfaces/msg/Log -c
1
```

Add 'topic find' verb

---

ros2service/ros2service/verb/type.py
ros2service/setup.py

Add the `type` verb to `service` which return the type of a given service.
E.g.
given `ros2 run demo_nodes_cpp talker`
```terminal
$ ros2 service type /talker/describe_parameters
rcl_interfaces/srv/DescribeParameters
```

Add 'service type' verb

---

ros2service/ros2service/verb/find.py
ros2service/setup.py

Add the `find` verb to `service` which lists all services of a given type.
E.g.
given `ros2 run demo_nodes_cpp talker` & `ros2 run demo_nodes_cpp listener`
```terminal
$ ros2 service find rcl_interfaces/srv/ListParameters
/listener/list_parameters
/talker/list_parameters
```
or with count-topics option,
```
$ ros2 service find rcl_interfaces/srv/ListParameters -c
2
```

add 'service find' verb

---

ros2pkg/ros2pkg/verb/xml.py
ros2pkg/setup.py

Add the `xml` verb to `pkg`.  
By default it prints the whole xml manifest of a given package. User can request for a particular tag with the `--tag` option.
E.g.
```terminal
$ ros2 pkg xml demo_nodes_cpp -t version
0.7.6
$
$ ros2 pkg xml demo_nodes_cpp -t test_depend
ament_cmake_pytest
ament_lint_auto
ament_lint_common
launch
launch_testing
launch_testing_ament_cmake
launch_testing_ros
```

Add pkg xml verb

---

ros2pkg/ros2pkg/verb/create.py

Renames the `package_format` flag to `package-format`, matching other flags using hyphen delimiters
Resolves #290

fix rename package-format to match other flags (#290)

---

ros2interface/ros2interface/api/__init__.py

Add actions to interface type completer

---

ros2topic/ros2topic/verb/bw.py

Precisely what the title says. `ros2 topic bw` output units are all bytes per second now. Connected to #304.

Fix ros2 topic bw output units.

---

ros2node/ros2node/verb/list.py

For node name order to be deterministic. Connected to #304.

Alphasort ros2 node list output.

---

ros2param/test/test_verb_dump.py

Connected to https://github.com/ros2/rclpy/pull/396; this fix is needed for CI to pass.
Signed-off-by: Juan Ignacio Ubeira <jubeira@ekumenlabs.com>

ros2param: consider automatic declaration for 'use_sim_time'

---

ros2action/ros2action/api/__init__.py
ros2action/ros2action/verb/send_goal.py

Add an action goal prototype completer to `ros2 action send_goal`.  
E.g.
```terminal
$ ros2 action send_goal /fibonacci action_tutorials/action/Fibonacci [tab][tab]
-f          --feedback  order:\ 0\ 
```
Not very pretty but one can at least figure out the first few characters of the goal body.
Then,
```terminal
$ ros2 action send_goal /fibonacci action_tutorials/action/Fibonacci "o [tab]
```
resolves to,
```terminal
$ ros2 action send_goal /fibonacci action_tutorials/action/Fibonacci "order: 0"
```
This follows the work initiated in https://github.com/ros2/ros2cli/pull/298.

Add action send_goal prototype completer

---

ros2topic/ros2topic/api/__init__.py
ros2topic/ros2topic/verb/pub.py

Add a message prototype completer to `ros2 topic pub`.  
E.g.
```terminal
$ ros2 topic pub /chatter geometry_msgs/msg/Pose [tab][tab]
-1
-n
--node-name
--once
-p
position:^J  x: 0.0^J  y: 0.0^J  z: 0.0^Jorientation:^J  x: 0.0^J  y: 0.0^J  z: 0.0^J  w: 0.0
--print
--qos-durability
--qos-profile
--qos-reliability
-r
--rate
```
Not very pretty but one can at least figure out the first few characters of the message body.
Then,
```terminal
$ ros2 topic pub /chatter geometry_msgs/msg/Pose "p [tab]
```
resolves to,
```terminal
ros2 topic pub /chatter geometry_msgs/msg/Pose "position:
x: 0.0
y: 0.0
z: 0.0
orientation:
x: 0.0
y: 0.0
z: 0.0
w: 0.0"
```
This follows the work initiated in https://github.com/ros2/ros2cli/pull/298.

Add topic pub prototype completer

---

ros2service/ros2service/api/__init__.py
ros2service/ros2service/verb/call.py

Add a service request prototype completer to `ros2 service call`.  
E.g.
```terminal
$ ros2 service call /add_two_ints example_interfaces/srv/AddTwoInts [tab][tab]
a:\ 0\^Jb:\ 0\  -r              --rate
```
Not very pretty but one can at least figure out the first few characters of the request body.
Then,
```terminal
$ ros2 service call /add_two_ints example_interfaces/srv/AddTwoInts "a [tab]
```
resolves to,
```terminal
ros2 service call /add_two_ints example_interfaces/srv/AddTwoInts "a: 0
b: 0"
```
This follows the work initiated in https://github.com/ros2/ros2cli/pull/298.

Add service call prototype completer

---

test_ros2cli/package.xml
test_ros2cli/test/config_ros2action_test.py

The original package was refactored into action_tutorials_py and action_tutorials_interfaces in https://github.com/ros2/demos/pull/378
Resolves https://github.com/ros2/build_cop/issues/222
Linux CI Before: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7830)](https://ci.ros2.org/job/ci_linux/7830/)
CI after:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7833)](http://ci.ros2.org/job/ci_linux/7833/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3902)](http://ci.ros2.org/job/ci_linux-aarch64/3902/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6390)](http://ci.ros2.org/job/ci_osx/6390/)
* Windows [![Build …

Rename action_tutorials dependency

---

ros2node/ros2node/verb/info.py

Addresses flake8 C412 errors introduced by flake8-comprehension 2.2.0
https://github.com/adamchainz/flake8-comprehensions/blob/master/README.rst#c412-unnecessary-list-comprehension---in-can-take-a-generator
See ros2/build_cop#228
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7867)](http://ci.ros2.org/job/ci_linux/7867/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3928)](http://ci.ros2.org/job/ci_linux-aarch64/3928/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6420)](http://ci.ros2.org/job/ci_osx/6420/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=7727)](http://ci.ros2.org/job/ci_windows/7727/)

Convert list comprehension to generator

---

test_ros2cli/package.xml
test_ros2cli/test/config_ros2action_test.py

Fixes https://github.com/ros2/ros2cli/issues/313.
For a reason I don't understand, after we split `action_tutorials` in `action_tutorials_py` and `action_tutorials_interfaces`, launch_testing can't kill `fibonacci_action_server` and the test fails (before we were installing a script and running it with `python ...`. Now we are installing it using console scripts entry points, that already installs an executable).
I switched to `action_tutorials_cpp` executable and it works well now.
I will dig in the real problem later, this is just for having green CI.

Change action_tutorials_py for action_tutorials_cpp

---

ros2doctor/README.md
ros2doctor/package.xml
ros2doctor/ros2doctor/api/__init__.py
ros2doctor/ros2doctor/api/format.py
ros2doctor/ros2doctor/api/network.py
ros2doctor/ros2doctor/api/platform.py
ros2doctor/ros2doctor/command/doctor.py
ros2doctor/setup.py

Import error added in `network.py` as a temporary fix for `ifcfg` module. Will remove and update with build dependency once a `deb` package is ready.
This is an enhancement to `report` feature based on previous discussion https://github.com/ros2/ros2cli/pull/319#discussion_r317217343 
This PR adds `--report_failed` argument, which allows user to only print report of failed checks. Major changes happen in `format.py` and `doctor.py` files. 
Report content is output from each check module and indexed by their module names in `generate_report()`. They are printed out by calling `format_print(modules, report)`. The function takes module names and print out their indexed report, with dynamically allocated space padding computed by `compute_padding`.

Update report feature with new argument, add temp fix for ifcfg module 

---

ros2component/ros2component/api/__init__.py

Fix #321.
There is a raise condition, as I described [here](https://github.com/ros2/ros2cli/issues/321#issuecomment-524834399).
The error I'm catching comes from here:
https://github.com/ros2/rclpy/blob/8da91cee54b68f1108ca017da885496ffb5ae16c/rclpy/src/rclpy/_rclpy.c#L3137-L3146
The problem is that I can be also hiding some other errors by doing this.
`rcl_get_service_names_and_types_by_node` is a wrapper of `rmw_get_service_names_and_types_by_node`.
`rmw_get_service_names_and_types_by_node` can fail not only because the node name wan't found, but also because allocation problems, etc (it depends on the rmw implementation); and I don't have a way to identify the error above from `rclpy` or above layers.
Ideally, the best way of solving this would be to list the services of all nodes, …

Handle find_container_node_names error

---

ros2doctor/ros2doctor/api/network.py

Flags can be either lowercase or uppercase dependent on the system. This change checks for both cases.

Make network check case-insensitive

---

ros2interface/package.xml
ros2interface/ros2interface/api/__init__.py
ros2interface/ros2interface/verb/proto.py
ros2interface/setup.py

Add `ros2 interface proto` verb.
This new verb prints a given interface prototype, e.g.
Topic : 
```terminal
$ ros2 interface proto geometry_msgs/msg/Pose
"position:
x: 0.0
y: 0.0
z: 0.0
orientation:
x: 0.0
y: 0.0
z: 0.0
w: 0.0
"
```
Service : 
```terminal
$ ros2 interface proto example_interfaces/srv/AddTwoInts 
"a: 0
b: 0
"
```
Action : 
```terminal
$ ros2 interface proto example_interfaces/action/Fibonacci
"order: 0
"
```
This new verb comes handy while scripting, but the main point was to figure out the pieces to get an interface prototype completer to be used in other cli tools.

Add interface proto 

---

ros2doctor/README.md
ros2doctor/package.xml
ros2doctor/ros2doctor/api/__init__.py
ros2doctor/ros2doctor/api/format.py
ros2doctor/ros2doctor/api/network.py

This PR tells windows and osx users to install `ifcfg` with `pip`, handles the error cases when package fails to be imported and when network check/report is unable to run. It adds additional type check for check result and report, to make sure when custom plug-in is implemented incorrectly, the process does not break.

Add warning and error handling for `ifcfg` import on Windows and OSX

---

ros2doctor/ros2doctor/api/__init__.py
ros2doctor/ros2doctor/api/network.py
ros2doctor/ros2doctor/api/platform.py
ros2doctor/ros2doctor/command/doctor.py

Adds arg `--include-warning/-iw` to ros2doctor CLI. It reports both warnings and errors as failed checks, while the default only includes errors. It can be used in combination with `--report-failed/-rf` or by itself when running `ros2 doctor` checks. It lets users choose how extensive the checks and reports cover.

ros2doctor: add `--include-warning` arg

---

ros2component/ros2component/api/__init__.py

Resolves https://github.com/ros2/ros2cli/issues/337
This is a backport of #322, but with a small change.
Since `NodeNameNonExistentError` doesn't exist in Dashing, we use the more generic `RuntimeError` instead.

[dashing] Handle find_container_node_names error (#322)

---

ros2doctor/ros2doctor/api/topic.py
ros2doctor/setup.py
ros2doctor/test/test_topic.py

Check for cases like pub without sub or sub without pub using `ros2topic` and `ros2cli` API. Report contains same content as `ros2 topic info` outputs. Also adds unit tests for `TopicCheck` and `TopicReport`.

ros2doctor: add topic check

---

ros2node/ros2node/api/__init__.py
ros2node/ros2node/verb/info.py

Resolves #344 
Adds separate action category to `ros2 node info`. Output looks like 
```
clairewang@karr:~/ros2_ws/src/ros2/ros2cli/ros2node$ ros2 node info /fibonacci_action_server /fibonacci_action_server
Subscribers:
Publishers:
/fibonacci/_action/feedback: action_tutorials_interfaces/action/Fibonacci_FeedbackMessage
/fibonacci/_action/status: action_msgs/msg/GoalStatusArray
/parameter_events: rcl_interfaces/msg/ParameterEvent
/rosout: rcl_interfaces/msg/Log
Services:
/fibonacci/_action/cancel_goal: action_msgs/srv/CancelGoal
/fibonacci/_action/get_result: action_tutorials_interfaces/action/Fibonacci_GetResult
/fibonacci/_action/send_goal: action_tutorials_interfaces/action/Fibonacci_SendGoal …
```

ros2node info: add action category

---

ros2multicast/setup.py

Otherwise, we see an error every time we run a ros2 command:
Failed to load entry point 'multicast': No module named 'ros2node.command.multicast'
Bug introduced in #346

Fix multicast entrypoint

---

ros2param/ros2param/api/__init__.py
ros2param/ros2param/verb/delete.py
ros2param/ros2param/verb/get.py
ros2param/ros2param/verb/set.py

For the `get` and `delete` verbs. Also naming the argument `parameter_name` (rather than `name`) in the usage.

add completion for parameter name arguments

---

ros2pkg/ros2pkg/api/create.py
ros2pkg/ros2pkg/resource/ament_python/main.py.em
ros2pkg/ros2pkg/resource/ament_python/setup.cfg.em
ros2pkg/ros2pkg/resource/ament_python/setup.py.em
ros2pkg/ros2pkg/resource/ament_python/test_copyright.py.em
ros2pkg/ros2pkg/resource/ament_python/test_flake8.py.em
ros2pkg/ros2pkg/resource/ament_python/test_pep257.py.em
ros2pkg/ros2pkg/verb/create.py

Backports `ros2 pkg create --build-type ament_python` from #296 to assist with ros2/ros2_documentation#362.
This PR does change two command line arguments `--cpp-node-name` and `--cpp-library-name` to `--node-name` and `--library-name`. I think that breakage is acceptable since it seems unlikely someone has automated calls to `ros2 pkg create` CLI, and backporting means the ROS 2 tutorial for package creation will work for Dashing.

Backport creating ament python packages to dashing

---

ros2param/ros2param/api/__init__.py
ros2param/ros2param/verb/describe.py
ros2param/setup.py

Fixes #362.
I chose to use the parameter name as the item without indentation and all other keys are then indented one level. That works nicely for multiple parameters and doesn't use extra empty lines. See example output:
```
$ ros2 param describe turtlesim background_r background_g
Parameter name: background_r
Type: integer
Description: Red channel of the background color
Constraints:
Min value: 0
Max value: 255
Parameter name: background_g
Type: integer
Description: Green channel of the background color
Constraints:
Min value: 0
Max value: 255
Additional constraints: foo
```

add ros2 param describe

---

ros2interface/ros2interface/api/__init__.py

Precisely what the title says. A #304 spin-off, comprehensive test coverage can be found there.

Handle bad or missing package on ros2 interface show

---

ros2cli/package.xml
ros2cli/ros2cli/daemon/__init__.py
ros2cli/ros2cli/node/daemon.py
ros2cli/ros2cli/verb/daemon/start.py

The problem is that when the IP address changes (e.g.: by DHCP), discovery doesn't work all the time.
This is a first proposal for solving the problem. 
I'm doing the following:
The methods registered in the `XMLRPC` server now check if one IP has changed, and in that case the `DirectNode` used by the Daemon is reset.
When the `DirectNode` is reset, the requested method is immediately call. Maybe an `spin_time` should be added (for ensuring enough discovery time).
With "checking that one IP has changed", I'm referring to the following -> If the IP address of any interface that has a gateway has changed, the `DirectNode` is reset.
As far as I understand, it's not possible to know what interface is the `rmw` implementation using.
Python doesn't have in the standard library a package for …

Make daemon “reset” itself when the IP address changes

---

ros2topic/package.xml
ros2topic/ros2topic/api/__init__.py
ros2topic/ros2topic/verb/echo.py
ros2topic/ros2topic/verb/pub.py
ros2topic/test/test_echo_pub.py
ros2topic/test/test_qos_conversions.py

Expose the same QoS settings to `ros2 topic echo` as were exposed to `ros2 topic pub` in https://github.com/ros2/ros2cli/pull/238
Fixes https://github.com/ros2/ros2cli/issues/281
Closes https://github.com/ros-security/aws-roadmap/issues/57
Blocked by #304

Expose qos durability and reliability to ros2topic echo

---

ros2interface/ros2interface/verb/show.py

Follow-up after #371. This pull request ensures `ros2 interface show` fails nicely, with no traceback.

Make ros2 interface show fail gracefully (no traceback)

---

ros2component/ros2component/api/__init__.py
ros2node/ros2node/api/__init__.py
ros2node/ros2node/verb/info.py

Changes behavior so that hidden names are not shown by default.
Before this change, if we ran turtlesim and retrieved the node info we'd see hidden topics and services related to the action server, e.g.
$ ros2 run turtlesim turtlesim_node
```sh
$ ros2 node info /turtlesim
/turtlesim
Subscribers:
/parameter_events: rcl_interfaces/msg/ParameterEvent
/turtle1/cmd_vel: geometry_msgs/msg/Twist
Publishers:
/parameter_events: rcl_interfaces/msg/ParameterEvent
/rosout: rcl_interfaces/msg/Log
/turtle1/color_sensor: turtlesim/msg/Color
/turtle1/pose: turtlesim/msg/Pose
/turtle1/rotate_absolute/_action/feedback: turtlesim/action/RotateAbsolute_FeedbackMessage
/turtle1/rotate_absolute/_action/status: action_msgs/msg/GoalStatusArray
Services:
/clear: std_srvs/srv/Empty
/kill: turtlesim/srv/Kill …
```

[ros2node] Add option to info verb to display hidden names

---

ros2topic/test/test_echo_pub.py

In case a subprocess hangs, then we are not waiting forever.

[ros2topic] Add test timeout for tests using subprocess

---

ros2topic/test/test_echo_pub.py

Closes #375. As a side note, running these tests against RTI Connext or ADLINK Opensplice fails -- which can now be easily configured by applying the following patch:
```bash
--- a/ros2topic/test/test_echo_pub.py
+++ b/ros2topic/test/test_echo_pub.py
@@ -35,6 +35,8 @@ from rclpy.qos import DurabilityPolicy
from rclpy.qos import QoSProfile
from rclpy.qos import ReliabilityPolicy
+from rmw_implementation import get_available_rmw_implementations
+
from std_msgs.msg import String
@@ -43,7 +45,7 @@ TEST_NAMESPACE = 'cli_echo_pub'
@pytest.mark.rostest
-@launch_testing.parametrize('rmw_implementation', ['rmw_fastrtps_cpp'])
+@launch_testing.parametrize('rmw_implementation', get_available_rmw_implementations())
@launch_testing.markers.keep_alive
def generate_test_description(rmw_implementation, …
```

Refactor test_echo_pub.py pytest into a launch test

---

ros2doctor/ros2doctor/command/doctor.py

The message previously said, for example
```
Failed modules are  network
```
Which is confusing when there's only one module
Changing to:
```
Failed modules: network
```
Which works if there's one or more failed modules

Update failed modules message

---

ros2interface/test/test_cli.py

Broken in https://github.com/ros2/rosidl_runtime_py/pull/6

[ros2interface] Fix tests

---

ros2topic/ros2topic/verb/info.py
ros2topic/test/test_cli.py
ros2topic/test/test_info.py

Display the type(s) of a given topic
Print an error message for unknown topics
<details>
<summary>For known topics</summary>
before:
```
$ ros2 topic info /chatter
Topic: /chatter
Publisher count: 0
Subscriber count: 1
```
after:
```
$ ros2 topic info /chatter
Type: std_msgs/msg/String
Publisher count: 0
Subscriber count: 1
```
</details>
<details>
<summary>For unknown topics</summary>
before:
```
$ ros2 topic info /unknown
Topic: /unknown
Publisher count: 0
Subscriber count: 0
```
after:
```
$ ros2 topic info /unknown
Unknown topic '/unknown'
```
</details>

[ros2topic] make info verb display the type of the topic

---

ros2topic/test/test_echo_pub.py

This pull request ensures we:
1. Stop re-using the same `rclpy` context, node and executor across tests. This causes failures on Linux-aarch64 when using Opensplice.
2. Force tests using `rmw_fastrtps*_cpp` to run before those using `rmw_opensplice_cpp`. Otherwise, we get failures for the former on Windows 10.  
My guess for (1.) is that publisher, subscriber, timer, etc. creation/destruction or even executor spinning on one test is negatively affecting others, whereas (2.) is simply mind blowing. Someway, somehow, `rmw_opensplice_cpp` is affecting `rmw_fastrtps_cpp` if run consecutively, not even simultaneously, on the same process. I've left TODOs and NOTES, we need to come back to this at some point, when we have more time.

Fix ros2topic test_echo_pub.py test suite

---

ros2component/ros2component/api/__init__.py
ros2node/ros2node/api/__init__.py
ros2node/ros2node/verb/info.py
ros2node/test/test_cli.py

Currently `ros2 node info` shows only service servers:
```
$ ros2 run demo_nodes_py add_two_ints_client &
$ ros2 node info /add_two_ints_client
/add_two_ints_client
Subscribers:
Publishers:
/parameter_events: rcl_interfaces/msg/ParameterEvent
/rosout: rcl_interfaces/msg/Log
Services:
/add_two_ints_client/describe_parameters: rcl_interfaces/srv/DescribeParameters
/add_two_ints_client/get_parameter_types: rcl_interfaces/srv/GetParameterTypes
/add_two_ints_client/get_parameters: rcl_interfaces/srv/GetParameters
/add_two_ints_client/list_parameters: rcl_interfaces/srv/ListParameters
/add_two_ints_client/set_parameters: rcl_interfaces/srv/SetParameters
/add_two_ints_client/set_parameters_atomically: rcl_interfaces/srv/SetParametersAtomically
Action Servers:
Action Clients:
```
After this PR: …

add service clients to ros2node info

---

ros2lifecycle/package.xml
ros2lifecycle/test/test_cli.py
ros2lifecycle_test_fixtures/CMakeLists.txt
ros2lifecycle_test_fixtures/package.xml
ros2lifecycle_test_fixtures/src/simple_lifecycle_node.cpp

Precisely what the title says. This pull requests adds integration for each and every `ros2 lifecycle` verb.
~It current depends on the `lifecycle` package in the `ros2/demos` repository, creating a circular repo dependency. Fixture nodes must be duplicated and relocated, maybe simplifying these in the process.~

[ros2lifecycle] Add test coverage for CLI

---

ros2cli/ros2cli/node/direct.py
ros2topic/ros2topic/verb/pub.py

`ros2 topic pub` has a `--node-name` option, but it appears to not do anything. This PR fixes that by making the direct_node take a keyword argument `node_name`.
To reproduce:
This should publish a string message on the topic `/foo/asdf`
```
ros2 topic pub -n "foo" "~/asdf" std_msgs/msg/String "data: be"
```
Without this PR, it appears the node name was not changed.
```
$ ros2 topic list --include-hidden-topics
/_ros2cli_982/asdf
```

Fix ros2 topic pub --node-name

---

ros2action/ros2action/api/__init__.py
ros2msg/ros2msg/api/__init__.py
ros2pkg/ros2pkg/verb/create.py
ros2srv/ros2srv/api/__init__.py
ros2topic/ros2topic/api/__init__.py

Address new linter warnings.
It didn't make sense that the functions were already sorting their return value since in several cases the caller doesn't care about the order. Therefore I moved the sorting to the callers where applicable.

fix new linter warnings as of flake8-comprehensions 3.1.0

---

ros2topic/ros2topic/api/__init__.py

Follow up of #283. @emersonknapp FYI.
Show the actually used default value whn calling `--help`.
Requires ros2/rclpy#463.

[ros2topic] show default values for --qos-* options

---

ros2doctor/ros2doctor/api/network.py

Warn about missing flags on windows `ipconfig` output. Closes #403 - false negative warnings on windows.

Update network check to fix missing flags on Windows 

---

ros2node/ros2node/verb/info.py
ros2node/test/test_cli.py

As the title says, this PR enables the flag for the info verb in ros2node since it was ignored for hidden nodes.

[ros2node] Make use of include-hidden flag for ros2node info verb

---

ros2action/ros2action/verb/show.py
ros2action/test/test_cli.py

This is a follow-up to #363, as we've consolidated interface CLI logic to ros2interface.

[eloquent] [ros2action] Deprecate show verb 

---

ros2topic/test/test_cli.py

After https://github.com/ros2/rcutils/pull/190, some test cases started failing:
https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_release/983/testReport/junit/ros2topic.test/test_cli/test_cli/
This PR corrects the test.

Add timestamp to ros2topic test where needed

---

ros2node/ros2node/api/__init__.py
ros2node/ros2node/verb/info.py

Fixes #417 by reverting #409 and only adding the API for cross-distro compatibility.
The other parts (fetching client information as well as the hidden topic option require other changes which are not available in Dashing).

partially revert [dashing backport] add service clients to ros2node info

---

ros2cli/ros2cli/daemon/__init__.py
ros2cli/ros2cli/node/strategy.py

Connected to #419. This pull request:
- Augments daemon support for the ROS graph API. 
- Adds a `--no-daemon` option for `NodeStrategy` client code to use and allow users to NOT use nor spawn a daemon.

Extend CLI daemon based features

---

ros2topic/ros2topic/api/__init__.py
ros2topic/ros2topic/verb/echo.py
ros2topic/ros2topic/verb/pub.py
ros2topic/test/fixtures/repeater_node.py

Connects to #218.
Note that the action feedback logic in the echo verb was incorrect, resulting in a ModuleImportError.
The new logic added in https://github.com/ros2/rosidl_runtime_py/pull/9 should fix the error.
Depends on https://github.com/ros2/rosidl_runtime_py/pull/9

[ros2topic] Use import message logic provided by rosidl_runtime_py

---

ros2topic/ros2topic/verb/info.py

According #411, support show hidden topic info with `ros2 topic info <hidden topic>`
However, I'm not sure whether it's fine to show hidden topic directly or it's necessary to add extra option, like `--include-hidden-topics`.

Able to show info of hidden topic.

---

ros2pkg/ros2pkg/verb/create.py

There's no ament_python package to depend on, it just uses setuptools directly. 
Also fix syntax for cmake type.
This will cause a rosdep error after following: https://index.ros.org/doc/ros2/Tutorials/Creating-A-ROS2-Package/
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8957)](http://ci.ros2.org/job/ci_linux/8957/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4727)](http://ci.ros2.org/job/ci_linux-aarch64/4727/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7329)](http://ci.ros2.org/job/ci_osx/7329/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8874)](http://ci.ros2.org/job/ci_windows/8874/)

fix create_pkg dependencies for python

---

ros2action/ros2action/command/action.py
ros2cli/ros2cli/cli.py
ros2cli/ros2cli/command/__init__.py
ros2cli/ros2cli/command/daemon.py
ros2cli/ros2cli/entry_points.py
ros2cli/ros2cli/plugin_system.py
ros2component/ros2component/command/component.py
ros2interface/ros2interface/command/interface.py
ros2lifecycle/ros2lifecycle/command/lifecycle.py
ros2multicast/ros2multicast/command/multicast.py
ros2node/ros2node/command/node.py
ros2param/ros2param/command/param.py
ros2pkg/ros2pkg/command/pkg.py
ros2service/ros2service/command/service.py
ros2topic/ros2topic/command/topic.py

Follow up of #424.
The changes are split over four commits to ease the review.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9081)](http://ci.ros2.org/job/ci_linux/9081/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4828)](http://ci.ros2.org/job/ci_linux-aarch64/4828/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=7432)](http://ci.ros2.org/job/ci_osx/7432/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=9019)](http://ci.ros2.org/job/ci_windows/9019/)

only load required entry points which improves the performance

---

ros2cli/ros2cli/command/__init__.py

Introduced in #436: https://ci.ros2.org/job/ci_linux/9126/testReport/ros2cli.test/test_flake8/test_flake8/
```
./ros2cli/command/__init__.py:93:9: Q000 Remove bad quotes
"`ros2cli.command.add_subparsers_on_demand` instead", stacklevel=2)
^
1     Q000 Remove bad quotes
```

fix linter warning about bad quotes

---

ros2param/ros2param/command/param.py

Fixes #440 which was a regression of #436.
Same fix as ros2/sros2#175.
CI build only testing `ros2param`: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9139)](https://ci.ros2.org/job/ci_linux/9139/)

fix ros2param tests

---

ros2cli/ros2cli/node/direct.py

Otherwise, all CLI arguments will be parsed as ROS arguments, which can lead
to rcl warnings or incorrect legacy remapping behavior.
This change does not pass arguments to rclpy.init from any of the CLI
tools, but it leaves the opportunity to do so in the future by setting the
parser argument 'argv'. For example, we could take the remaining arguments
and pass them to rclpy.init, similar to what is done in ros2run:
https://github.com/ros2/ros2cli/blob/4c5d9327026ecb2ea10a16b3429908b4f6f64ca6/ros2run/ros2run/command/run.py#L51-L53
Fixes #336.
* Linux [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=9150)](https://ci.ros2.org/job/ci_linux/9150/) (test failure [occurring on nightly](https://ci.ros2.org/view/nightly/job/nightly_linux_release/1426/testReport/junit/ros2act …

Avoid passing None to rclpy.init

---

ros2pkg/ros2pkg/verb/create.py

Currently the generated packages fail to pass rosdep making them hard to reuse.
Ideally this would be backported and released in Dashing as well.
Note: The tutorials refering to this invalid builtool dependency explicitly would need to be updated. That'll make them valid when used with the nightly archives as well that don't list that dependency.

Request for backport of 428 to eloquent

---

ros2cli/ros2cli/command/__init__.py

override parse_known_args for completion to work with partial argparse tree

---

ros2doctor/package.xml
ros2doctor/ros2doctor/command/doctor.py
ros2doctor/ros2doctor/verb/__init__.py
ros2doctor/ros2doctor/verb/call.py
ros2doctor/ros2doctor/verb/hello.py
ros2doctor/setup.py
ros2doctor/test/test_hello.py
ros2doctor/test/test_topic.py

> How about a verb called “yell” (or something more clever), where the program just spins and sends “hello-world” and it’s hostname once per second, over both a hard-coded ROS2/DDS topic and a “custom” multicast UDP packet as well. At the same time, it is listening for other messages on that same ROS2 topic and/or UDP multicast port and printing a summary table periodically of which other hosts it has heard from, message counts, and so on. This would help debug the current #1 problem we are seeing, where people have messaging working on localhost but can’t receive those messages on another host. This spins into a debug cycle of trying to figure out if the problem lies with their software, their network configuration, DDS discovery or transport bugs, the network infrastructure, and so on. …

Multimachine communication

---

ros2cli/ros2cli/node/direct.py

[Eloquent Backport] Avoid passing None to rclpy.init (#433)

---

ros2doctor/ros2doctor/api/__init__.py
ros2doctor/ros2doctor/api/format.py
ros2doctor/ros2doctor/api/network.py
ros2doctor/ros2doctor/api/package.py
ros2doctor/ros2doctor/api/platform.py
ros2doctor/ros2doctor/api/topic.py
ros2doctor/ros2doctor/command/doctor.py

Updates in this PR:
* Decouple `doctor_warn()` and `Result()` to improve error/warning trace-back
before, warning always trace back to the `format.py` file
```
/home/claire/ros2_ws/build/ros2doctor/ros2doctor/api/format.py: 76: 
UserWarning: Distribution foxy is not fully supported or tested. 
To get more consistent features, download a stable version at https://index.ros.org/doc/ros2/Installation/
```
now, warning points to the exact file where things go wrong
```
/home/claire/ros2_ws/build/ros2doctor/ros2doctor/api/platform.py:76:
UserWarning: Distribution foxy is not fully supported or tested. 
To get more consistent features, download a stable version at https://index.ros.org/doc/ros2/Installation/
```
* Add `doctor_error()` in addition to `doctor_warn()`, to differentiate warning and …

[ros2doctor] Improve doctor_warn() 

---

ros2topic/ros2topic/verb/info.py
ros2topic/test/test_cli.py

**NOTE: DO NOT MERGE until [rmw #186](https://github.com/ros2/rmw/pull/186),  [rmw_implementation #72](https://github.com/ros2/rmw_implementation/pull/72),  [rcl #511](https://github.com/ros2/rcl/pull/511) and [rclpy #454](https://github.com/ros2/rclpy/pull/454) are merged.**
This PR makes the necessary changes to implement [this](https://github.com/ros2/rmw/issues/151) feature request. Once all the dependent PRs are merged, the `ros2cli` layer can now use the `node.get_publishers_info_by_topic` and `node.get_subscriptions_info_by_topic` functions to enhance the output of `ros2 topic info <topic_name>` as follows:
```
$ ros2 topic info rosout
Topic              : rosout
Publisher count    : 2
Node Name: _NODE_NAME_UNKNOWN_
Node Namespace: _NODE_NAMESPACE_UNKNOWN_
Topic Type: …
```

Enhanced ros2 topic info to display node name, node namespace, topic type and qos profile of the publishers and subscribers.

---

ros2action/test/test_cli.py
ros2lifecycle/test/test_cli.py
ros2node/test/test_cli.py
ros2service/test/test_cli.py
ros2topic/test/test_cli.py

This is to give time for discovery to happen between the daemon node and the test fixture nodes.
Alternative to https://github.com/ros2/ros2cli/pull/454
Depends on https://github.com/ros2/launch/pull/390

Add delay when retrying tests involving the CLI daemon

---

ros2action/test/test_cli.py
ros2lifecycle/test/test_cli.py
ros2node/test/test_cli.py
ros2service/test/test_cli.py
ros2topic/test/test_cli.py

Moved `get_available_rmw_implementations` function from `rmw_implementation` to `rclpy`  
- https://github.com/ros2/rclpy/pull/517
- https://github.com/ros2/rmw_implementation/pull/85

using get_available_rmw_implementations from rclpy

---

ros2doctor/ros2doctor/verb/hello.py

This fixes an error when the hostname starts with an illegal character for a node name (e.g. a number).

Prefix ros2doctor node names with 'ros2doctor_'

---

ros2action/test/test_cli.py
ros2interface/test/test_cli.py
ros2node/test/test_cli.py
ros2pkg/test/test_cli.py
ros2service/test/test_cli.py
ros2topic/test/test_cli.py
ros2topic/test/test_echo_pub.py

The ready_fn will be deprecated in the future in favor of the ReadyToTest() action in launch_testing. See ros2/launch#346 (comment) for background information
Signed-off-by: Pete Baughman <pete.baughman@apex.ai>

Remove ready_fn, self.proc_info

---

ros2node/ros2node/api/__init__.py
ros2node/ros2node/verb/info.py
ros2node/test/test_cli_duplicate_node_names.py

Second half of https://github.com/ros2/ros2cli/issues/453 
Second half of https://github.com/ros-tooling/aws-roadmap/issues/196
Add a simple warning for `ros2 node info` when there is more than one node with the same name. This does not change functionality at all, just informs users of a potentially confusing situation.
Signed-off-by: Emerson Knapp <emerson.b.knapp@gmail.com>

Add a warning to ros2 node info when there is more than one node with the same name

---

ros2node/ros2node/api/__init__.py
ros2node/ros2node/verb/list.py
ros2node/test/test_node.py

First half of https://github.com/ros2/ros2cli/issues/453 
First half of https://github.com/ros-tooling/aws-roadmap/issues/196
Add a simple warning, and annotate which nodes it applies to, when `ros2 node list` lists multiple nodes with the same exact name.  Within the "request for design" discussion https://github.com/ros2/design/issues/187, there was confusion expressed about where multiple names come from, whether they are artifacts of the printing process. This at least clears that up a little bit -it does not change the functionality at all.

Add warning and annotation to `ros2 node list` when there are non-unique nodes

---

ros2node/test/test_cli.py
ros2service/test/test_cli.py

This updates tests in ros2service and ros2node to expect no launch_ros node. These tests have [been failing since March 18](http://build.ros2.org/view/Fci/job/Fci__nightly-fastrtps_ubuntu_focal_amd64/61) and failed last night on [nightly release](http://build.ros2.org/view/Fci/job/Fci__nightly-release_ubuntu_focal_amd64/), [nightly debug](http://build.ros2.org/view/Fci/job/Fci__nightly-debug_ubuntu_focal_amd64/), [nightly connext](http://build.ros2.org/view/Fci/job/Fci__nightly-connext_ubuntu_focal_amd64/), [nightly cyclone](http://build.ros2.org/view/Fci/job/Fci__nightly-cyclonedds_ubuntu_focal_amd64/), [nightly fastrtps](http://build.ros2.org/view/Fci/job/Fci__nightly-fastrtps_ubuntu_focal_amd64/),  and [nightly fastrtps dynamic](http://build.ros2.org/view/Fci/job/Fci__nightly-fastrtps-d …

Update tests to expect no launch_ros node

---

ros2topic/ros2topic/verb/echo.py
ros2topic/ros2topic/verb/info.py
ros2topic/ros2topic/verb/pub.py

**_Depends on [ros2/rclpy:459](https://github.com/ros2/rclpy/pull/459)_**
Related to the feature discussed [here](https://github.com/ros2/ros2/issues/822). This PR handles the `ON_REQUESTED_INCOMPATIBLE_QOS` and `ON_OFFERED_INCOMPATIBLE_QOS` callback events on `ros2 topic echo` and `ros2 topic pub` commands respectively. 
This way, users now will get a warning when they `echo/pub` to a topic with incompatible QoS Policies.
Signed-off-by: Jaison Titus <jaisontj92@gmail.com>

[WIP] Added incompatible event support to ros2 topic echo and ros2 topic pub

---

ros2topic/ros2topic/verb/info.py
ros2topic/test/test_cli.py

Currently when `ros2 topic info` is used in verbose mode, there is a vertical space between the "Publisher count: x" heading and the list of publishers below it. That vertical space is missing for the "Subscription count: x" heading and the list of subscriptions below it.
This pull request adds that vertical spacing to the subscriptions listing, so that it is consistent with the publishers listing.

Fix formatting of "ros2 topic info -v" output

---

ros2doctor/ros2doctor/api/topic.py

Before the tool was generating many false positives as it is a valid configuration
to have an unequal number of publishers and subscriptions on a given topic.
This change makes it so we only provide a warning if one of the counts is zero and the
other is not. Although this is still a legitimate configuration, it seems more likely to be
a problem and worth reporting.

[ros2doctor] Only report topic warnings if publisher or subscription count is zero

---

ros2pkg/ros2pkg/verb/create.py

Use the local git configuration when querying the `user.email` key instead of
the global configuration. Fixes #477
Signed-off-by: Thibaud Chupin <thibaud.chupin@spaceapplications.com>

Use local git config instead of global for email

---

ros2param/test/test_verb_dump.py

Fixes #480.
Catch expected exceptions from rclpy (or transitively as xmlrpc.client.Fault) while we wait for discovery in the test setup.

[ros2param] Wait for discovery before running tests

---

ros2param/ros2param/verb/list.py

If the node use default node option ( start_parameter_services is ture) and use not spin() but spin_until_future_complete(), then ros2param list send a request to the node but the callback of parameter service list parameter request can not be called. and ros2param spin_until_future_complete can not be finished.

[ros2param] Add timeout to ros2param list

---

ros2param/test/test_verb_dump.py

Follow-up to #481
This makes the tests faster.

[ros2param] Do not wait for entire timeout in test_verb_dump setUp

---

ros2action/test/test_cli.py
ros2interface/test/test_cli.py
ros2lifecycle/test/test_cli.py
ros2node/test/test_cli.py
ros2node/test/test_cli_duplicate_node_names.py
ros2pkg/test/test_cli.py
ros2service/test/test_cli.py
ros2topic/test/test_cli.py
ros2topic/test/test_echo_pub.py

We've been lacking on Windows test data for months due to the blocking
or hung state that these tests can get into. I think the best thing to
do is skip these tests on windows to allow other builds to complete
while we continue investigating the problem.
I've opted for skipping entire test modules as I think the underlying issue is in the test apparatus rather than any specific test.

Skip CLI tests on Windows until we resolve the blocking/hanging isuse.

---

ros2lifecycle/test/test_cli.py
ros2node/test/test_cli.py
ros2node/test/test_cli_duplicate_node_names.py
ros2service/test/test_cli.py
ros2topic/test/test_cli.py

The Node parameter 'node_executable' has been deprecated and replaced
with the parameter 'executable'.
Depends on https://github.com/ros2/launch_ros/pull/140

Replace deprecated launch_ros usage

---

ros2topic/ros2topic/verb/bw.py
ros2topic/test/test_cli.py

This PR fixes a few issues I noticed while using `ros2topic bw`.
* Use `time.monotonic()` so time measurements aren't affected by system clock time jumps
* Fix units on printed message sizes - they're sizes not size per second
* Don't use any decimal places when printing bytes, continue using 2 decimal places with KB and MB
* Make the periodic print easier to understand (subjective)
* It wasn't clear to me what `window:` was, so output now says it's a measurement considering that many messages
* mean/min/max are sizes not bandwidth so output now includes word "size"
* Use `f` strings
What the current output in `eloquent` looks like:
```
$ ros2 topic bw /topic
Subscribed to [/topic]
average: 61.08B/s
mean: 28.00B/s min: 28.00B/s max: 28.00B/s window: 2
average: 58.43B/s
mean: 28.00B/s min: …
```

[ros2topic bw] Monotonic clock, units, fstring

---

ros2param/package.xml
ros2param/test/fixtures/parameter_node.py
ros2param/test/test_verb_dump.py

Fixes https://github.com/ros2/ros2cli/issues/480
The actual tests are the same, except with the use of launch_testing we ensure the CLI daemon
is restarted between tests. This follows a similar pattern as the other ros2cli tests.
I've left a TODO to test with all RMW implementations. I did not enable this now  since I do
not expect the tests to pass with all RMW implementations.
See https://github.com/ros2/ros2cli/issues/482

[ros2param] Convert test_verb_dump into launch test

---

ros2doctor/setup.py

Without this, `ros2 extensions` doesn't list `ros2doctor.hello` as one of the sub-verbs.  I think this was just an oversight.

Make sure to add ros2doctor verbs to the extension points.

---

ros2topic/ros2topic/verb/pub.py
ros2topic/test/test_echo_pub.py

While doing some testing, it turned out to be useful to tell `ros2 topic pub` exactly how many times to publish a message.  This is basically a generic version of the `-1` flag that already exists, though that flag is left for backwards-compatibility.
I should point out that this is *not* the same as doing `for i in seq 1 10 ; do ros2 topic pub ... ; done`.  The difference is that with the bash loop, a new node and publisher is created every time.  This can be problematic for discovery, since it can happen that we bring up the node, publish, and destroy the node before connections are properly made.  Doing it inside of `ros2 topic pub` itself neatly avoids this issue.
The one potentially flaky part of this is the test, which …

Implement times for ros2 topic pub

---

ros2cli/package.xml
ros2cli/ros2cli/daemon/__init__.py
ros2cli/ros2cli/node/daemon.py
ros2cli/ros2cli/node/direct.py
ros2cli/ros2cli/node/strategy.py
ros2cli/ros2cli/xmlrpc/__init__.py
ros2cli/ros2cli/xmlrpc/client.py
ros2cli/ros2cli/xmlrpc/local_server.py
ros2cli/ros2cli/xmlrpc/marshal/__init__.py
ros2cli/ros2cli/xmlrpc/marshal/generic.py
ros2cli/ros2cli/xmlrpc/marshal/rclpy.py
ros2cli/test/test_daemon.py

Split from #421. This pull request extends the CLI daemon API to better match that of a regular `rclpy.node.Node`.

Extend CLI daemon's API

---

ros2cli/ros2cli/daemon/__init__.py
ros2cli/test/test_daemon.py

to enable https://github.com/ros2/sros2/pull/203

add support for get_node_names_and_namespaces_with_enclaves

---

ros2cli/test/test_daemon.py

Fixes https://github.com/ros2/ros2cli/issues/503. Some RMW implementations are slow enough to make this graph API-intensive test flakey. This pull requests attempts to circumvent that problem.

Make test_daemon.py robust to discovery latency.

---

ros2topic/ros2topic/verb/delay.py

I changed the help string for `ros2 topic delay` from `Topic name to be calcurated the delay` to `Topic name to calculate the delay for`.

Fix typo in `ros2 topic delay` help

---

ros2interface/ros2interface/verb/proto.py
ros2interface/ros2interface/verb/show.py
ros2service/ros2service/verb/call.py
ros2topic/ros2topic/verb/pub.py

Using single quotes inside double quotes is consistent with the other CLI help messages.

Use consistent quotes in help messages

---

ros2doctor/ros2doctor/verb/hello.py
ros2doctor/test/test_api.py
ros2doctor/test/test_cli.py

Precisely what the title says. Came across this while testing `ros2 doctor hello` on a VM that had dashes in its hostname. It's tricky one to test for regression, so I'm open to ideas.

Ensure ros2doctor ROS nodes have valid names.

---

ros2interface/package.xml
ros2interface/ros2interface/verb/package.py
ros2interface/ros2interface/verb/proto.py
ros2interface/ros2interface/verb/show.py
ros2interface/test/test_cli.py

Packages were deprecated in https://github.com/ros2/common_interfaces/pull/116.
This also fixes a [test failure](https://ci.ros2.org/view/nightly/job/nightly_linux_release/1548/testReport/ros2interface.src.ros2.ros2cli.ros2interface.test/test_cli/test_cli/) introduced by the deprecation notice.

[ros2interface] Remove usage of deprecated std_msgs and std_srvs packages

---

ros2interface/ros2interface/verb/show.py
ros2interface/test/test_cli.py

Implements #349.
Interface types can now be piped directly into show, like this:
`$ ros2 topic type /chatter | ros2 interface show`

[ros2interface] Allow stdin input for 'ros2 interface show'

---

ros2component/ros2component/api/__init__.py
ros2component/ros2component/verb/list.py

Precisely what the title says. No matter the amount of container nodes in the system. Closes #507.
Ideally, I'd like `rclpy` executors to support asynchronous code and to have some ROS graph events at hand. For the time being, this will do.

Ensure consistent timeout in ros2component list.

---

ros2doctor/ros2doctor/verb/hello.py
ros2doctor/test/test_cli.py

For better resource management and to avoid races in tests. Hopefully this resolves race in [Windows CI]( https://ci.ros2.org/view/nightly/job/nightly_win_rel/1564/testReport/junit/ros2doctor.src.ros2.ros2cli.ros2doctor.test/test_cli/test_cli/).

Refactor ros2doctor hello verb.

---

ros2doctor/package.xml
ros2doctor/ros2doctor/api/platform.py
ros2doctor/ros2doctor/command/doctor.py

The ros2doctor [package check](https://github.com/ros2/ros2cli/blob/d109a695b0630b139f30c979ec9133836ae77fb0/ros2doctor/ros2doctor/api/package.py#L38) requires ROS_DISTRO to be defined in the environment.  If it is not, you get warnings like:
```
UserWarning: ERROR: ROS_DISTRO is not set
```
Since that environment variable comes from the `ros_environment` package, that means this package has an `exec_depend` on `ros_environment`.  Add that here.
While we are in here, also notice that platform.py returns a "None" value if `_check_platform_helper` fails.  However, it's contract states:
```
:return: Report object storing report content.
```
Thus, make sure to return an empty report on error, which fixes possible crashes and also conforms to what other reports do.
Signed-off-by: Chris …

Make ros2doctor depend on ros_environment and fix platform.py bug on error.

---

ros2topic/ros2topic/verb/pub.py

The new option allows to make the currently hard coded sleep before exiting configurable. It also change the logic to apply that sleep for `times != 1` since even when publishing multiple messages it makes sense to wait after the last one to ensure it is published to the wire.
CI builds testing `ros2topic`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11339)](http://ci.ros2.org/job/ci_linux/11339/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6576)](http://ci.ros2.org/job/ci_linux-aarch64/6576/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9302)](http://ci.ros2.org/job/ci_osx/9302/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11236)] …

add --keep-alive option to 'topic pub'

---

ros2interface/ros2interface/verb/show.py

Previously, inline comments on constants were not able to be removed; now they adopt the same display behavior as other comments.

[ros2interface] Fixes inline comments for constants

---

ros2topic/test/fixtures/listener_node.py
ros2topic/test/test_cli.py

Follow up of #544. Fix flakiness of `pub_once` test added in #304.
E.g. https://ci.ros2.org/view/nightly/job/nightly_linux-centos_extra_rmw_release/459/testReport/ros2topic.ros2topic.test/test_cli/test_cli/
CI build testing `ros2topic`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11341)](http://ci.ros2.org/job/ci_linux/11341/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6578)](http://ci.ros2.org/job/ci_linux-aarch64/6578/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9304)](http://ci.ros2.org/job/ci_osx/9304/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11238)](http://ci.ros2.org/job/ci_windows/11238/)

use transient_local and longer keep-alive for pub tests

---

ros2topic/ros2topic/verb/echo.py
ros2topic/ros2topic/verb/find.py
ros2topic/ros2topic/verb/info.py
ros2topic/ros2topic/verb/list.py
ros2topic/ros2topic/verb/type.py

fixes #511
added daemon support to the other topic tools, except pub.
Signed-off-by: Dereck Wonnacott <dereck.wonnacott@havalus.com>

Enable --no-daemon flag for some cli tools

---

ros2topic/test/fixtures/listener_node.py
ros2topic/test/test_cli.py

The `TestROS2TopicCLI` tests perform feature testing of the ros2topic command line interface. If the system is under stress during these tests, messages may be lost (by design). If that happens, there is a fairly high likelihood that the `test_topic_pub_once` test will fail because there is only one opportunity for the message to be successfully transported. We're likely dropping other messages in this suite, but the other tests continuously publish until one of the messages is received (or a timeout occurs), making them significantly less likely to fail.
Using the 'reliable' setting for QoS reliability seems to make the tests consistently pass, even when the system is placed under additional stress.
Closes #552
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&buil …

Use reliable QoS for ros2topic tests

---

ros2topic/ros2topic/api/__init__.py
ros2topic/ros2topic/verb/echo.py
ros2topic/ros2topic/verb/pub.py

Closes #557.
CI builds testing only `ros2topic` with Fast DDS:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11725)](http://ci.ros2.org/job/ci_linux/11725/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6809)](http://ci.ros2.org/job/ci_linux-aarch64/6809/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9564)](http://ci.ros2.org/job/ci_osx/9564/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11663)](http://ci.ros2.org/job/ci_windows/11663/)

improve the error message for invalid message types

---

ros2cli/package.xml

Following https://github.com/ros2/ros2_documentation/pull/841#issuecomment-682203981 here's a proposal so that all ros2cli commands no longer require a manual install of python3-argcomplete
TODO: to be updated in https://github.com/ros2/ros2_documentation also

Added dependency to python3-argcomplete to ros2cli

---

ros2param/ros2param/api/__init__.py
ros2param/ros2param/verb/describe.py
ros2param/ros2param/verb/list.py

address https://github.com/ros2/ros2cli/issues/569
Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>

add "--param-type" option to ros2param list.

---

ros2topic/ros2topic/verb/echo.py
ros2topic/test/test_cli.py

A new '--filter' option makes it easy to echo only part of a message.
For example, to only echo the position part of an odometry message:
ros2 topic echo /odom --filter pose/pose/position
The filter option takes one value that must not be empty (or only forward slashes '/').
--- 
I found that this feature was a bit easier to add after refactoring the code a little bit. I did the refactor in a separate commit to make the review easier (ae07bd5):
* Move subscription functions into class for easier reuse arguments.
* Prefix functions with an underscore to indicate they are private.

Add filter option to ros2topic 

---

ros2cli/ros2cli/entry_points.py
ros2doctor/ros2doctor/api/__init__.py

The importlib_metadata package is a backport of the importlib.metadata module from Python 3.8. Fedora (and possibly others) no longer package importlib_metadata because they ship Python versions which have the functionality built-in.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13460)](http://ci.ros2.org/job/ci_linux/13460/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8371)](http://ci.ros2.org/job/ci_linux-aarch64/8371/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11184)](http://ci.ros2.org/job/ci_osx/11184/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13524)](http://ci.ros2.org/job/ci_windows/13524/)

Support Python 3.8-provided importlib.metadata

---

ros2pkg/package.xml

Requires ros/rosdistro#28001.
Used here:
https://github.com/ros2/ros2cli/blob/f6c4a5b05d172f8156645b8fcf8bd2dfa23e7bb2/ros2pkg/ros2pkg/api/create.py#L20-L23
The source code supports using the `importlib_resources` package, but on all of the platforms we're running regular builds for, we have Python 3.7, which provides the package as part of Python itself.

Declare missing dependency on python3-importlib-resources

---

ros2cli/ros2cli/command/__init__.py

Use argcomplete's split_line to deal with incomplete quote states.
Signed-off-by: Daisuke Sato <daisukes@cmu.edu>

bugfix for #563

---

ros2param/ros2param/api/__init__.py
ros2param/ros2param/verb/load.py
ros2param/setup.py
ros2param/test/fixtures/parameter_node.py
ros2param/test/test_verb_load.py

Example execution:
```
ros2 param  load /controller_manager ~/controller_manager.yaml 
Set parameter diff_drive_controller.type successful
Set parameter forward_command_controller_position.type successful
Set parameter joint_state_controller.type successful
```
```
ros2 param  load /controller_manager ~/controller_manager.yaml  --use-wildcard 
Set parameter mystr successful
Set parameter diff_drive_controller.type successful
Set parameter diff_drive_controller.type successful
Set parameter forward_command_controller_position.type successful
Set parameter joint_state_controller.type successful
```
Using the following file:
```yaml
controller_manager:
ros__parameters:
diff_drive_controller:
type: diff_drive_controller/DiffDriveController
forward_command_controller_position:
type: …
```

Add rosparam verb load

---

ros2param/ros2param/verb/list.py
ros2param/test/test_verb_list.py

Examples:
```
ros2 param list --filter '(?!qos_overrides)'
ros2 param list --filter 'prefix_for_group_of_settings_i_care.*'
```
I'm not sure if we want exactly this or something else...
TODO: tests

Add --filter options for 'ros2 param list'

---

ros2param/ros2param/api/__init__.py
ros2param/ros2param/verb/dump.py
ros2param/test/test_verb_dump.py
ros2param/test/test_verb_load.py

Make `ros2 param dump` consistent with how `rclcpp` and `rclpy` load parameters.
See for example https://github.com/ros2/rclcpp/blob/ab743392e4daf546eb0de704936b5f14ef6e0417/rclcpp/src/rclcpp/node_interfaces/node_parameters.cpp#L97.

ros2 param dump/load should use fully qualified node names

---

ros2param/ros2param/api/__init__.py
ros2param/ros2param/verb/load.py
ros2param/test/test_verb_load.py

Add wildcard loading to ros2 param load

---

ros2param/test/test_verb_list.py

Fixes https://github.com/ros2/ros2cli/issues/604
There were problems with `rmw_connext_cpp`.

Make the ros2param --filter test more reliable

---

ros2param/ros2param/api/__init__.py
ros2param/ros2param/verb/dump.py
ros2param/ros2param/verb/load.py
ros2param/setup.py
ros2param/test/fixtures/parameter_node.py
ros2param/test/test_verb_dump.py
ros2param/test/test_verb_load.py

* Add rosparam verb load
Signed-off-by: Victor Lopez <victor.lopez@pal-robotics.com>
* Move load_parameter_file implementation to api, add test_verb_load
Signed-off-by: Victor Lopez <victor.lopez@pal-robotics.com>
* Apply fixes for linter
Signed-off-by: Victor Lopez <victor.lopez@pal-robotics.com>
* Remove TODO comment
Signed-off-by: Victor Lopez <victor.lopez@pal-robotics.com>
* Fix linter errors
Signed-off-by: Audrow Nash <audrow.nash@gmail.com>
Co-authored-by: Audrow Nash <audrow.nash@gmail.com>

Foxy backport Add rosparam verb load (#590)

---

ros2topic/ros2topic/verb/list.py
ros2topic/test/test_cli.py

According to #347, the PR adds option `-v` to show more info for topic list.

Add verbose info for topic list

---

ros2cli/ros2cli/node/daemon.py
ros2cli/ros2cli/xmlrpc/local_server.py
ros2cli/test/test_strategy.py

Improvement over #620. Flakes in `ros2cli`'s test_strategy.py such as [this one](https://ci.ros2.org/view/nightly/job/nightly_win_rep/lastCompletedBuild/testReport/ros2cli.ros2cli.test/test_strategy/test_with_no_daemon_running_3_3_/) were due to TOCTOU races between an `is_daemon_running` check and a `socket.bind` within the spawned daemon process. This patch does not resolve that race (not trivial, see discussion in #620), but ensures only one daemon can successfully bind to the same address.
CI up to `ros2cli`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14378)](http://ci.ros2.org/job/ci_linux/14378/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9153)](http://ci.ros2.org/job/ci_linux-aarch64/9153/)
* …

Ensure only one daemon can run at a time

---

ros2doctor/ros2doctor/api/__init__.py

This PR fixes a bug in the `ros2 doctor` utility.
Both the `run_checks` and the `generate_reports` functions contain a for loop that iterates over all the specified entry points.
If there are issues with one of the entry points, the exception is catched and a warning is printed.
However, after printing the warning, the loop continues executing.
This causes a problem as variables such as `check_class`, `report_class`, `check_instance` and `report_instance` may still hold the value assigned during the previous iteration of the loop.
Let's assume that we have 2 reports: A and B, with B raising an `ImportError` during `report_entry_pt.load()`.
This will result in printing twice the report from A.
This PR adds a `continue` after the warnings.
Signed-off-by: Alberto Soragna …

continue to next iteration after exceptions in generate_reports and

---

ros2pkg/ros2pkg/resource/ament_python/setup.cfg.em

Get rid of these warnings:
```
c:\python38\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
warnings.warn(
c:\python38\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
warnings.warn(
--- stderr: my_package
c:\python38\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
warnings.warn(
c:\python38\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated …
```

[ros2pkg] Use underscores in setup.cfg.em instead of dashes

---

ros2doctor/ros2doctor/api/__init__.py
ros2doctor/ros2doctor/api/qos_compatibility.py
ros2doctor/ros2doctor/api/topic.py
ros2doctor/setup.py
ros2doctor/test/fixtures/listener_node_with_reliable_qos.py
ros2doctor/test/fixtures/talker_node_with_best_effort_qos.py
ros2doctor/test/fixtures/talker_node_with_reliable_qos.py
ros2doctor/test/test_qos_compatibility.py

Here is an example of what the check looks like if an incompatibility error is detected;
```
/root/ros2_ws/build/ros2doctor/ros2doctor/api/qos_compatibility.py: 49: UserWarning: ERROR: QOS compatibility error found on topic '/my_chatter'. Use `ros2 doctor --report` for more details.
```
Here is what a report looks like with two pub/sub pairs, one compatible and one incompatible:
```
QOS COMPATIBILITY LIST
topic [type]            : /chatter [std_msgs/msg/String]
publisher node          : talker
subscriber node         : listener
compatibility status    : OK
topic [type]            : /my_chatter [std_msgs/msg/String]
publisher node          : mynode
subscriber node         : mynode
compatibility status    : ERROR: Best effort publisher and reliable subscription;
```
The messages for …

[ros2doctor] Add QoS compatibility check and report

---

ros2topic/ros2topic/api/__init__.py
ros2topic/ros2topic/verb/echo.py
ros2topic/ros2topic/verb/pub.py

First iteration. Connects to #594 
Signed-off-by: Gonzalo de Pedro <gonzalo@depedro.com.ar>

QoS autodetection

---

ros2doctor/ros2doctor/api/__init__.py
ros2doctor/ros2doctor/api/network.py
ros2doctor/ros2doctor/api/package.py
ros2doctor/ros2doctor/api/platform.py

The output of `ros2 doctor` on Windows was confusing.
* Print an useful error message when failing to import rosdistro.
* Print a clearer error message when failing to find either a loopback or no loopback interface on Windows.
* Print "latest version" instead of "required version".
* Print the corrent name of the python executable according to the platform.
See the comment I wrote in the Galactic testing matric for more context.
`rosdistro` python package is not usually installed on Windows, so having a nicer message when not found is helpful.
I updated "latest version" to "required version" because the warning shows that for that ros distribution there's a newer version of the package available in rosdistro, it's not really a required version.

Improve ros2 doctor on Windows

---

ros2topic/test/test_cli.py

Connected to https://github.com/ros2/rclpy/pull/722
Fixes the output tests given the new printing info.

Fix Topic Info Test with "Infinite" printing

---

ros2topic/ros2topic/verb/pub.py

address https://github.com/ros2/ros2cli/issues/624

`ros2 topic pub` starts publishing right away.

---

ros2pkg/ros2pkg/api/create.py
ros2pkg/ros2pkg/resource/package_environment/package.xml.em

Hi @audrow, here's my fix for #619.
I tested it with ` pytest ros2pkg/test/test_cli.py`, which checks that the build type is being written to `package.xml` successfully [(here)](https://github.com/ros2/ros2cli/blob/master/ros2pkg/test/test_cli.py#L205) .
I also confirmed manually that `package.xml` looked correct (indentation, spacing between lines looked good).
Let me know if any further changes or tests are needed.

Pass package exports to template in pkg create api (#619)

---

ros2pkg/ros2pkg/api/__init__.py
ros2pkg/test/test_api.py

Changes in https://github.com/ament/ament_index/pull/69 adds a possible ValueError to `get_package_prefix` when the package name is invalid.
This PR handles this case identically to a missing package by returning `None` from the API call.

Handle ValueError

---

ros2topic/ros2topic/verb/pub.py
ros2topic/test/test_cli.py
ros2topic/test/test_echo_pub.py

Replaces https://github.com/ros2/ros2cli/pull/641, seems to be a better idea to me.

Add option in ros2 topic pub to wait for N matching subscriptions, use N=1 by default when combined with --times

---

ros2component/ros2component/api/__init__.py

Closes #530.
CI up to `ros2component`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14731)](http://ci.ros2.org/job/ci_linux/14731/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9482)](http://ci.ros2.org/job/ci_linux-aarch64/9482/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12396)](http://ci.ros2.org/job/ci_osx/12396/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14876)](http://ci.ros2.org/job/ci_windows/14876/)

Drop deprecated get_container_components_info() API.

---

ros2param/ros2param/verb/dump.py
ros2param/test/test_verb_dump.py
ros2param/test/test_verb_load.py

address https://github.com/ros2/ros2cli/issues/625

add '--write' option to avoid an unintentional data loss.

---

ros2pkg/package.xml
ros2pkg/ros2pkg/verb/create.py
ros2pkg/test/test_cli.py

That is, if the '--license' command-line argument is one of
the ones that ament_copyright knows, fetch the license text
out of ament_copyright and place it in 'LICENSE' at the
root of the package.
Here's the current list of strings that will trigger the creation of the LICENSE file:
* Apache License, Version 2.0
* Boost Software License - Version 1.0
* BSD License 2.0
* 2-Clause BSD License
* 3-Clause BSD License
* GNU General Public License 3.0
* GNU Lesser General Public License 3.0
* MIT License
* MIT-0 License
One thing to be aware of here is that this is the first use of `ament_copyright` in an `exec_depend`.  I don't think that should be a problem, but it is something to think about.
An enhancement we could do here is to …

Generate LICENSE files on ros2 pkg create.

---

ros2cli/ros2cli/daemon/__init__.py
ros2cli/ros2cli/daemon/daemonize.py
ros2cli/ros2cli/helpers.py
ros2cli/ros2cli/node/daemon.py
ros2cli/ros2cli/node/network_aware.py
ros2cli/ros2cli/verb/daemon/start.py
ros2cli/ros2cli/verb/daemon/status.py
ros2cli/ros2cli/verb/daemon/stop.py
ros2cli/ros2cli/xmlrpc/local_server.py
ros2cli/test/test_daemon.py
ros2cli/test/test_strategy.py

This patch is an alternative to #632, transferring socket ownership on spawn to preclude the TOCTOU races that running daemon checks induce. 
This patch is functional in my local Linux environment. Let's see what CI (and Windows) have to say:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14866)](http://ci.ros2.org/job/ci_linux/14866/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9616)](http://ci.ros2.org/job/ci_linux-aarch64/9616/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12533)](http://ci.ros2.org/job/ci_osx/12533/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15034)](http://ci.ros2.org/job/ci_windows/15034/)

Transfer daemon socket ownership on spawn.

---

ros2param/ros2param/verb/list.py
ros2param/test/test_verb_list.py

I think this relates to https://github.com/ros2/ros2cli/issues/655, and hopefully fixes it.
By using the daemon node to list parameter services, I hope we avoid a race with discovery with every invocation of `ros2 param list`. There still is a race with the first call if the daemon is not running yet, but I think that's normal for most ros2cli tools.
I've also add a retry decorator to the test to workaround it potentially failing on the first try.

Fix flaky ros2 param list

---

ros2cli/ros2cli/cli.py

Fixes https://github.com/ros2/ros2cli/issues/595.
This forces all calls to print() to also flush the output buffer, the result is similar to having line buffering.
Alternative: We could also do something like what it's suggested here https://stackoverflow.com/questions/107705/disable-output-buffering.
Another alternative: I don't think we need unbuffered output for all commands though, e.g. it's not needed for `ros2 topic list`.
The ones that need unbuffered (or line buffered) output are the ones that are periodically reporting progress, e.g. `ros2 topic pub`, `ros2 topic echo`, etc.
Some of that output could arguably be going to stderr, which in python is always line buffered (even when non interactive), e.g. the output of `ros2 topic pub`.
The output of `ros2 topic echo` should probably …

Make the ros2cli output always line buffered

---

ros2cli/ros2cli/cli.py

This reverts commit 0075a7174f4cb9a9a57efaa9811c314dd3bbb166.
@ivanpauno we need to revert this because of https://ci.ros2.org/job/ci_linux/15050/testReport/junit/ros2param.ros2param.test/test_verb_dump/test_verb_dump/
i confirmed that this can be reproducible.

Revert "Make the ros2cli output always line buffered (#659)"

---

ros2topic/ros2topic/api/__init__.py
ros2topic/ros2topic/verb/pub.py

Signed-off-by: Gonzalo de Pedro <gonzalo@depedro.com.ar>

Change default QoSProfile for pub

---

ros2param/ros2param/verb/list.py
ros2param/test/test_verb_list.py

[galactic backport] Fix flaky ros2 param list (#656)

---

ros2param/ros2param/verb/list.py

Backport #656 to Foxy.
Note, that the test code does not exist in Foxy, so that part was not backported.

[foxy backport] Fix flaky ros2 param list (#656)

---

ros2param/ros2param/api/__init__.py

Removed redundant code. ``rclpy.task.Future.result()`` already raises if there's an exception.
Brought up in https://github.com/ros2/launch_ros/pull/270
https://github.com/ros2/rclpy/blob/691e4fbfcb4bd4cc2a01182a7dced3105a78200b/rclpy/rclpy/task.py#L93-L94
Signed-off-by: Aditya Pande <aditya050995@gmail.com>

Removed redundant code

---

ros2topic/ros2topic/api/__init__.py
ros2topic/ros2topic/verb/echo.py
ros2topic/ros2topic/verb/pub.py
ros2topic/test/test_qos_conversions.py

Backporting work of #528 to foxy as discussed in issue #523 
cc: @clalancette 
---
support QoS Depth and History via ros2 topic pub/echo.
Also keep depth at least 1 with transient_local setting.

[BACKPORT] support QoS Depth and History via ros2 topic pub/echo. (#528)

---

ros2topic/package.xml
ros2topic/ros2topic/verb/bw.py
ros2topic/ros2topic/verb/delay.py
ros2topic/ros2topic/verb/hz.py

This was propagated due to an invalid license in ament_lint which is proposed to be fixed at: https://github.com/ament/ament_lint/pull/209

Cleanup mislabeled BSD license

---

ros2pkg/ros2pkg/resource/ament_cmake/CMakeLists.txt.em
ros2pkg/ros2pkg/resource/ament_python/test_copyright.py.em

The template sources populated through `ros2 pkg create` for the
`ament_python`/`ament_cmake` build types do not have well-formed
copyright headers, and as such fail the `ament_copyright` tests when
run as-is.
This commit skips said test by default, instead informing the user to -
once the source files have been populated with well-formed headers -
enable the skipped tests either within the test script itself (for
`ament_python`) or within the CMakeLists.txt file (for `ament_cmake`).
Addresses #675.
Signed-off-by: Abrar Rahman Protyasha <aprotyas@u.rochester.edu>

[ros2pkg] Skip copyright tests in template packages

---

ros2action/package.xml
ros2doctor/package.xml
ros2interface/package.xml
ros2lifecycle/package.xml
ros2node/package.xml
ros2pkg/package.xml
ros2service/package.xml
ros2topic/package.xml

ros_testing depends on ros2test which depends on ros2cli. This causes a circular dependency in the repository that means `ros-rolling-ros2cli` gets installed in the PR job for this repo.

Depend on launch packages instead of ros_testing to avoid circular dependency

---

ros2cli/ros2cli/node/direct.py

There was a change in signal handling, and now SIGINT/SIGTERM will automatically trigger a shutwon request.
This modifies `DirectNode.__exit__()` to use `try_shutdown()`, in order to not get a "context already shutdown" error when a signal is sent.
I manually tested with the following example and the issue is gone:
```py
import sys
from ros2cli.node.direct import DirectNode
args = sys.argv[1:]
with DirectNode(args) as node:
from rclpy.executors import SingleThreadedExecutor
executor = SingleThreadedExecutor()
executor.add_node(node)
executor.spin_once(timeout_sec=None)
```
New error message after ctrl-c:
```
^CTraceback (most recent call last):
File "audrow_example.py", line 10, in <module>
executor.spin_once(timeout_sec=None)
File …
```

Use try_shutdown() instead of shutdown() in DirectNode.__exit__()

---

ros2param/ros2param/api/__init__.py
ros2param/test/test_api.py

Basically ensure that we are *always* using the parsed yaml
string, so that users can override types as appropriate.
This makes it possible for users to specify something like:
ros2 param set /node param '!!str off'
for force a string to be "off" as opposed to having YAML
intepret it as a boolean.
This is still a draft because I'm kind of nervous about the change; this has the potential to break some use-cases that worked before.  All of the tests pass, and basic testing here has worked fine for me, but I want to do more testing before marking it as ready.
Fixes #677 (at least, as far as I think we can fix it)

Fix how ros2 param interprets command-line arguments.

---

ros2pkg/ros2pkg/verb/create.py

- This solves the issue reported in #477, which is fixed for ROS2
Elequent in #479, but not other distros.
Signed-off-by: aalbaali <albaalia@live.com>

Use local git config instead of global

---

ros2service/ros2service/verb/list.py
ros2service/test/test_cli.py

There's currently API in place for listing hidden services, however the command line option was never exposed.

also provide --include-hidden-services for `ros2 service list` verb

---

ros2topic/ros2topic/verb/echo.py

address https://github.com/ros2/ros2cli/issues/680

add yaml dump flow style.

---

pytest.ini
ros2action/package.xml
ros2cli/package.xml
ros2component/package.xml
ros2doctor/package.xml
ros2interface/package.xml
ros2lifecycle/package.xml
ros2multicast/package.xml
ros2node/package.xml
ros2param/package.xml
ros2pkg/package.xml
ros2run/package.xml
ros2service/package.xml
ros2topic/package.xml

This PR aims to remedy our buildfarm jobs that occasionally hang until they are manually killed. 
This requires the following PR: https://github.com/ros2/ci/pull/632.
You can see that the timeout worked to stop a job here (with absurdly low timeout): https://ci.ros2.org/job/ci_linux/16355/console#console-section-5.

Add timeout to kill hanging tests

---

ros2cli/ros2cli/entry_points.py
ros2doctor/ros2doctor/api/__init__.py

Use the newer select interface where available, but fallback
to the dict interface as needed.
Connects to https://github.com/ros2/ros2/issues/1254

Fix importlib_metadata warning on Python 3.10.

---

ros2topic/ros2topic/verb/bw.py

I want to reuse the collection and computation portions, but
not the CLI portions.  So split getting the data from printing
the data.

Split the bandwidth functions into a get and print.

---

ros2topic/ros2topic/verb/echo.py

Depends on https://github.com/ros2/rclpy/pull/922.
Exampler
``` bash
ros2 run demo_nodes_py talker
```
```# terminal 2
ros2 topic echo /chatter -v
```
<details>
<summary>Expected output</summary>
```
message_info:
source_timestamp: 1650489540621873147
received_timestamp: 1650489540622072614
publication_sequence_number: 857
message:
data: 'Hello World: 856'
---
message_info:
source_timestamp: 1650489541623013413
received_timestamp: 1650489541623204404
publication_sequence_number: 858
message:
data: 'Hello World: 857'
---
message_info:
source_timestamp: 1650489542623151805
received_timestamp: 1650489542623384098
publication_sequence_number: 859
message:
data: 'Hello World: 858'
---
```
</details>
```
ros2 topic echo /chatter -v --csv
```
<details>
<summary>Expected output</summary>
``` …
```

Add verbose option to echo that also prints the associated message info

---

ros2component/ros2component/verb/types.py

It never uses a node, so it should never have node-style
arguments.
Should fix #710

Remove unused arguments from ros2 component types.

---

ros2param/test/test_verb_dump.py
ros2param/test/test_verb_list.py
ros2param/test/test_verb_load.py

As the title says.
These tests are known to be flaky on Galactic, addressed for Humble. This PR marks them as xfail so the buildfarm skips testing them. 
See:
https://github.com/ros2/ros2cli/issues/630#issuecomment-925338671
Signed-off-by: Jorge Perez <jjperez@ekumenlabs.com>

:man_farmer: Mark known flaky tests as xfail

---

ros2cli_test_interfaces/package.xml

It is now properly included in the rosidl dependency chain.
Depends on https://github.com/ros2/rosidl_defaults/pull/22

Remove action_msgs dependency

---

ros2topic/ros2topic/verb/pub.py
ros2topic/test/test_pub.py

This PR enables expansion of `auto` to a generated `Header` whose `stamp` field is set to the current time. This also expands `now` to the current time if the field is of type `builtin_interfaces.msg.Time`
These changes match the same behavior that `rostopic` has:
http://wiki.ros.org/ROS/YAMLCommandLine#Headers.2Ftimestamps
Closes #700

Expand auto to the current time when passed to a Header field

---

ros2topic/package.xml
ros2topic/ros2topic/verb/bw.py
ros2topic/ros2topic/verb/hz.py
ros2topic/ros2topic/verb/pub.py
ros2topic/test/test_use_sim_time.py

Signed-off-by: Lei Liu <Lei.Liu.AP@sony.com>

Add support use_sim_time for ros2 topic hz/bw/pub.

---

ros2multicast/ros2multicast/api/__init__.py
ros2multicast/ros2multicast/verb/__init__.py
ros2multicast/ros2multicast/verb/receive.py
ros2multicast/ros2multicast/verb/send.py
ros2multicast/test/test_api.py

This PR allows specifying `--group` and `--port` to `ros2 multicast`. This is useful when debugging issues with multicast traffic for a specific group and domain id.

Add --group and --port options to ros2 multicast

---

ros2node/ros2node/verb/list.py

Signed-off-by: Michael Wrock
Updated wording for the warning displayed when multiple nodes share the same name

Updated wording in list.py

---

ros2pkg/ros2pkg/resource/ament_cmake/CMakeLists.txt.em
ros2pkg/ros2pkg/resource/cmake/CMakeLists.txt.em

Automatically add ALIAS targets for generated libraries, as it's best practice to have those. 
In creating this PR, I was unable to test it; after building this package and sourcing the install environment, the host ros2cli seems to still be used. 
Signed-off-by: Ryan Friedman <ryan_friedman@trimble.com>

Add alias library targets for CMake pkg generation

---

ros2param/test/test_verb_dump.py
ros2param/test/test_verb_list.py
ros2param/test/test_verb_load.py

In this issue: https://github.com/ros2/ros2cli/issues/630, is reported an issue with this test on Humble, and @sloretz [commented](https://github.com/ros2/ros2cli/issues/630#issuecomment-925338671) that the solution in https://github.com/ros2/ros2cli/pull/652, cannot be backported. 
As this issue is happening just on galactic, I'm marking the following tests as xfail:
* test_verb_load
* test_verb_dump
* test_verb_list
Reference build: https://build.ros2.org/view/Gci/job/Gci__nightly-debug_ubuntu_focal_amd64/179/
Running CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17564)](http://ci.ros2.org/job/ci_linux/17564/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=12102)](http://ci.ros2.org/job/ci_linux-aarch6 …

Mark test verb load, list and dump as xfail

---

ros2topic/test/test_use_sim_time.py

address flaky test: https://github.com/ros2/ros2cli/issues/772

Extend timeout to shutdown the command line process.

---

ros2topic/ros2topic/api/__init__.py
ros2topic/ros2topic/verb/echo.py
ros2topic/ros2topic/verb/pub.py
ros2topic/test/test_qos_conversions.py

For a subscription to have manual_by_topic liveliness, it means that it requires publishers to provide manual_by_topic liveliness (i.e. if not it won't match).
When a publisher uses manual_by_topic liveliness, liveliness is asserted when either a message is published or is asserted manually.
`ros2 topic pub` will only assert liveliness through publishing messages, and never manually.
Though this is not more useful than automatic liveliness, it's useful for testing. e.g. you have a subscription requiring manual_by_topic liveliness and you want `ros2 topic pub` to match it.
Also, deduplicated some code.

Allow configuring liveliness in ros2 topic echo and pub

---

ros2cli/completion/ros2-argcomplete.zsh

ZSH argcomplete: call compinit only if needed

---

ros2lifecycle_test_fixtures/CMakeLists.txt

The main reason to do this is so that we can compile the fixture with the clang static analyzer.  As of clang++-14 (what is in Ubuntu 22.04), the default still seems to be C++14, so we need to specify C++17 so that new things in the rclcpp headers work properly.
Further, due to reasons I don't fully understand, I needed to set CMAKE_CXX_STANDARD_REQUIRED in order for clang to really use that version.  So set this as well.

Update the ros2cli test fixture to C++17.

---

ros2topic/ros2topic/api/__init__.py
ros2topic/ros2topic/verb/bw.py
ros2topic/ros2topic/verb/delay.py
ros2topic/ros2topic/verb/hz.py
ros2topic/ros2topic/verb/pub.py

A lot of types across verbs in ros2 topic are shared. This PR refactors the types to be used by different verbs preventing redefinition of the same types in different verbs. There is no behaviour changed introduced.
Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>

Refactor common types

---

ros2param/ros2param/verb/get.py
ros2param/ros2param/verb/set.py

In the ros2param code, we get integer and double arrays as literal Python arrays.  When printing that out in ros2 param get, they look something like:
Double values are: array('d', [1.4, 1.5])
But that isn't really what we want the user to see.  So call .tolist() on these before we print, so it looks like:
Double values are: [1.4, 1.5]

Fix printing of integer and double arrays.

---

ros2topic/ros2topic/verb/echo.py
ros2topic/test/test_echo_pub.py

These were missed in a previous code review; fix them here.
Signed-off-by: Chris Lalancette <clalancette@gmail.com>
In particular, these problems were added in #792.  The issues were not caught in CI due to a bug in colcon (which has subsequently been fixed).  @arjo129 FYI.

Fix some flake8 warnings related to style.

---

ros2topic/ros2topic/verb/echo.py
ros2topic/ros2topic/verb/pub.py
ros2topic/test/test_echo_pub.py

Supercedes #797
When we run `ros2 topic pub -w 1 ...` we can wait for a fixed number
of connections prior to shutting down. This is useful in many scenarios,
however when writing automated tests it may be useful to time out if the
correct number of connections are not recieved in a given amount of
time. This PR adds a `--max-wait-time` option which allows users to set
a timeout on how long to wait for subscribers.
Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>

Adds a `--max-wait-time` option to `ros2 topic pub` 

---

ros2cli/ros2cli/helpers.py
ros2node/ros2node/api/__init__.py
ros2param/ros2param/verb/delete.py
ros2param/ros2param/verb/describe.py
ros2param/ros2param/verb/dump.py
ros2param/ros2param/verb/get.py
ros2param/ros2param/verb/load.py
ros2param/ros2param/verb/set.py
ros2param/test/test_verb_load.py

address https://github.com/ros2/ros2cli/issues/799

add timeout option for ros2param to find node.

---

ros2cli/ros2cli/helpers.py
ros2node/ros2node/api/__init__.py

Linux debug CI shows test regressions with test_flake8:
Reference build: [Linux Debug #2589](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2589/)
[ros2cli.ros2cli.test.test_flake8.test_flake8](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2589/testReport/junit/ros2cli.ros2cli.test/test_flake8/test_flake8/)
<details>
```
test/test_flake8.py:23: in test_flake8
assert rc == 0, \
E   AssertionError: Found 1 code style errors / warnings:
E     ./ros2cli/helpers.py:46:1: E302 expected 2 blank lines, found 1
E   assert 1 == 0
```
</details>
[ros2node.ros2node.test.test_flake8.test_flake8](https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2589/testReport/ros2node.ros2node.test/test_flake8/test_flake8/) 
<details>
```
test/test_flake8.py:23: in test_flake8
assert rc == …
```

Fix linters for `helpers.py` and `ros2node/api/__init__.py`

---

ros2topic/test/test_echo_pub.py

to fix https://github.com/ros2/ros2cli/issues/809
NOTE: There are some other ways to fix it. (use a reliable QoS, or even remove the publish times).

avoid flaky test that subscriber might not receive the message

---

ros2cli/ros2cli/node/__init__.py
ros2component/ros2component/api/__init__.py
ros2doctor/package.xml
ros2interface/package.xml
ros2node/package.xml

Fix missing `exec_depends` in `package.xmls` and docstrings to generate documentation without any warnings using `autodoc`
> Note: Without explictly casting `HIDDEN_NODE_PREFIX` to `str`, `autodoc` will throw an error as it cannot infer the type of this variable since dep modules are not imported.

Enable document generation using rosdoc2

---

ros2topic/ros2topic/verb/echo.py

This is part of https://github.com/ros2/ros2/issues/1361
qos_event was deprecated inside of rclpy in https://github.com/ros2/rclpy/pull/1058 , so use the new API names in this PR.
Part of https://github.com/ros2/ros2/issues/1361
Depends on https://github.com/ros2/rmw/pull/339
Depends on https://github.com/ros2/rcl/pull/1024
Depends on https://github.com/ros2/rclpy/pull/1058

Switch to using new event_handler instead of qos_event.

---

ros2topic/ros2topic/verb/pub.py

In particular, Python 3.11 on RHEL-9 doesn't seem to like the pipe syntax for an optional argument.  But we have the Optional marking available from typing, so switch to that instead.

Fix the type annotation in pub.py.

---

ros2cli/ros2cli/node/direct.py

Otherwise, the 'use_sim_time' parameter we are setting here is completely ignored.
@fujitatomoya FYI, this is a follow-up to #581

Set automatically_declare_parameters_from_overrides in DirectNode.

---

ros2topic/test/test_cli.py

Fixes tests with ros2/rclpy#1110

Expect type hash cli output in test

---

ros2action/package.xml
ros2doctor/package.xml
ros2interface/package.xml
ros2lifecycle/package.xml
ros2multicast/package.xml
ros2node/package.xml
ros2param/package.xml
ros2pkg/package.xml
ros2run/package.xml
ros2service/package.xml
ros2topic/package.xml

That is, they have no build step, so they shouldn't export a dependency for that.
@cottsay can you double-check my work on this one and make sure I'm not mistaken?  Thanks.

Make all of the dependencies in pure Python packages exec_depend.

---

ros2pkg/ros2pkg/verb/create.py

part of https://github.com/osrf/ros2_test_cases/issues/954

ros2pkg warning message typo fix.

---

ros2doctor/ros2doctor/verb/hello.py

Uncovered in tutorial party: https://github.com/osrf/ros2_test_cases/issues/548
There was an issue where `ros2 doctor hello` would not shutdown on Windows, instead hanging with the trace: 
```
Traceback (most recent call last):
File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
self.run()
File "C:\Python38\lib\threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "C:\ros2_iron\Lib\site-packages\rclpy\executors.py", line 280, in spin
self.spin_once()
File "C:\ros2_iron\Lib\site-packages\rclpy\executors.py", line 717, in spin_once
handler, entity, node = self.wait_for_ready_callbacks(timeout_sec=timeout_sec)
File "C:\ros2_iron\Lib\site-packages\rclpy\executors.py", line 703, in wait_for_ready_callbacks
return next(self._cb_iter)
File …
```

Shutdown ros2doctor hello when ctrl-c is received

---

ros2interface/ros2interface/verb/package.py
ros2interface/test/test_cli.py

Add interface type filters to ros2 interface package

---

ros2cli/ros2cli/xmlrpc/marshal/rclpy.py
ros2topic/ros2topic/verb/info.py
ros2topic/test/test_cli.py

Part of https://github.com/ros2/ros2/issues/1159
Depends on https://github.com/ros2/rclpy/pull/1104
Features
- Adds marshalling functions for `rclpy.type_hash.TypeHash`
- Adapt comment that type hash is also printed when doing `rostopic info --verbose`

Add marshalling functions for rclpy.type_hash.TypeHash (rep2011)

---

ros2param/ros2param/verb/dump.py

As mentioned in #836 , this pull request aims to correct the `ros2 param dump -h` information.
https://github.com/ros2/ros2cli/blob/960962a142323c7a13c4ddef3a7e661d77905f93/ros2param/ros2param/verb/dump.py#L31-L32
```python
class DumpVerb(VerbExtension):
"""Show all of the parameters of a node in a YAML file format."""
```
The current docstring for `ros2 param describe`
https://github.com/ros2/ros2cli/blob/960962a142323c7a13c4ddef3a7e661d77905f93/ros2param/ros2param/verb/describe.py#L27-L28
mixed with the documentation at 
https://docs.ros.org/en/rolling/How-To-Guides/Using-ros2-param.html#ros2-param-dump
```
This command will print out all of the parameters on a particular node in a YAML file format.
```
I'd be glad to update this PR as needed.

Update ros2 param dump dosctring (`-h` option).

---

ros2cli/ros2cli/daemon/__init__.py
ros2cli/ros2cli/node/direct.py
ros2param/test/test_verb_dump.py
ros2param/test/test_verb_list.py
ros2param/test/test_verb_load.py
ros2service/test/test_cli.py

Part of ros2/ros2#1159
Depends on ros2/rclpy#1139
ros2/rclpy#1139 starts a new service and introduces a new parameter to enable it. This PR fixes test expectations given the new situation, including turning _off_ the new service on the daemon node.

Fix tests with new service and param present

---

ros2action/ros2action/verb/send_goal.py
ros2cli/ros2cli/helpers.py
ros2service/ros2service/verb/call.py
ros2topic/ros2topic/verb/pub.py

Resolve #842
Add option `--stdin` to pass yaml from standard input.
The last positional argument and the new option `--stdin` are mutually_exclusive_group.
The change requires that the send_goal argument `goal` be optional.

Load a message/request/goal from standard input

---

ros2cli/ros2cli/node/daemon.py

to fix https://github.com/ros2/ros2cli/issues/851
Please refer to the https://github.com/ros2/ros2cli/pull/852#issuecomment-1716847919

make handles not inheritable to prevent from blocking durning tab-completion

---

ros2cli/package.xml
ros2cli/ros2cli/node/network_aware.py
ros2cli/ros2cli/xmlrpc/local_server.py

[netifaces](https://github.com/al45tair/netifaces) is unmaintained: https://github.com/al45tair/netifaces/issues/78.
It does not provide official prebuilt wheels for Python > 3.9: https://pypi.org/project/netifaces/#files
https://pypi.org/project/psutil/ is an alternative (available in rosdep as `python3-psutil`) but the interface is a little different.
The reason I'm making this change is that we want to upgrade to a Python>3.9 but not provide a compiler inside our CI container (Unrelated to this PR, but we're using Bazel with a standalone hermetic compiler toolchain and https://github.com/mvukov/rules_ros2). Not having a host compiler for Python wheel builds makes it more difficult to build netifaces.
There are only two `netifaces` usages in ros2cli:
**LocalXMLRPCServer**
It just needs …

Replace unmaintained `netifaces` library to avoid local wheel builds

---

ros2topic/ros2topic/verb/bw.py

It isn't needed, and will fix a warning on newer flake8.

Remove parentheses from assert statement.

---

ros2run/ros2run/api/__init__.py

On Python 3.6 (in RHEL-8), signal.valid_signals()
does not exist.  Only use it if it exists.
This should fix #879 .  Note that we only need this fix on Humble, since we don't have to worry about Python 3.6 on Iron and later.

Conditionally use valid_signals.

---

ros2cli/ros2cli/daemon/__init__.py

There are 2 fixes needed here:
1.  Make sure to check rclpy.ok() in the overall loop for handling requests.  That's because rclpy is handling the signals by default.
2.  Realize that server.handle_request() uses the set timeout as a timeout to select(), essentially.  Because of that, we instead set the timeout to a short value (200 milliseconds), and do the overall timeout checking ourselves.
Note that because we are waking up more often, this will cause the ros2 daemon to use more CPU than before.  But it should be negligible overall.
This should fix #885

Fix the SIGTERM handling in the ros2 daemon.

---

ros2cli/ros2cli/node/daemon.py

#852 remove inheritence of open fds to fix the issue. It use the soft-limit from RLIMIT_NOFILE to loop over all fds.
This breaks ros2cli on some Unices due to a high soft-limit,
https://github.com/ros2/ros2/issues/1531
This PR follows Ruby's approach of reading ~/proc/self/status~ to get fdsize for the loop-limit (as suggested by @clalancette in the bug-report).
Tested this on the latest osrf/ros:rolling-desktop.
Edit:
(lmk what I need to do to fix the ci).

ros2cli.node.daemon : try getting fdsize from /proc for open fd limit

---

ros2doctor/ros2doctor/api/network.py

We already depend on psutil, which can give us information for ros2doctor in a cross-platform way.  Lean more heavily into using this, which should help us deal with cross-platform a little more smoothly.
I will note that this slightly changes the output of ros2doctor on Linux.  Prior to this PR, the flags output would look something like:
```
flags        : 4163<MULTICAST,BROADCAST,UP,RUNNING>
```
After this PR, the output looks like this:
```
flags        : UP,BROADCAST,RUNNING,MULTICAST
```
That is, we lose the decimal bitmask associated with the device.
This should fix #906

Revamp how we get network information in ros2doctor.

---

ros2action/test/fixtures/fibonacci_action_server.py
ros2doctor/test/fixtures/listener_node_with_reliable_qos.py
ros2doctor/test/fixtures/talker_node_with_best_effort_qos.py
ros2doctor/test/fixtures/talker_node_with_reliable_qos.py
ros2node/test/fixtures/complex_node.py
ros2param/test/fixtures/parameter_node.py
ros2service/ros2service/verb/call.py
ros2service/test/fixtures/echo_server.py
ros2topic/test/fixtures/controller_node.py
ros2topic/test/fixtures/listener_node.py
ros2topic/test/fixtures/repeater_node.py
ros2topic/test/fixtures/talker_node.py
ros2topic/test/qos_subscription.py

This allows us to clean up things substantially, so we can still clean up after ourselves, but use less code doing so.
This is part of https://github.com/ros2/rclpy/issues/1280

Switch to using rclpy.init context manager.

---

ros2cli/test/test_daemon.py
ros2service/test/fixtures/introspectable.py

This ensures that we properly cleanup after ourselves

Switch to using the rclpy.init context manager.

---

ros2topic/test/test_echo_pub.py

minor cosmetic fix to remove TODO for https://github.com/ros2/rmw_opensplice

Remove TODO for OpenSplice DDS issue.

---

ros2topic/ros2topic/verb/hz.py
ros2topic/test/test_cli.py

replaces https://github.com/ros2/ros2cli/pull/831 and closes https://github.com/ros2/ros2cli/issues/830
Note: after the merge, we need to update the documentation

Support multiple topics via ros2 topic hz.

---

ros2topic/ros2topic/verb/echo.py
ros2topic/test/test_cli.py

Adds the `--clear/-c` option to echo.
Solves this issue: https://github.com/ros2/ros2cli/issues/725
This was previously available in ROS.
This clears the screen before a new message is displayed.
`ESC[2J` corresponds to `erase entire screen`
`ESC[H` corresponds to `moves cursor to home position (0, 0)`
I had to build rolling from source to successfully run the tests

feat(echo --clear): add --clear option to echo

---

ros2cli/ros2cli/node/strategy.py
ros2topic/ros2topic/verb/echo.py

closes https://github.com/ros2/ros2/issues/1614

NodeStrategy supports node name argument.

---

ros2cli/package.xml
ros2pkg/package.xml

This dependency is no longer used.
Follow-up to #537

Drop dependency on python3-pkg-resources

---

ros2cli/ros2cli/daemon/__init__.py
ros2cli/ros2cli/node/daemon.py
ros2cli/ros2cli/xmlrpc/local_server.py

Especially in tests where the daemon is being repeatedly created and destroyed, it can take some time for the kernel to actually allow the address to be rebinded (even after the old process has exited).  This can lead to some situations where we fail to spawn the daemon.
To fix this, set "allow_reuse_address" inside the LocalXMLRPCServer, which will set SO_REUSADDR on the socket.

Allow reuse address when firing up the ros2cli daemon.

---

ros2topic/ros2topic/verb/pub.py
ros2topic/test/resources/chatter.yaml
ros2topic/test/test_echo_pub.py

closes https://github.com/ros2/ros2cli/issues/919

support ros2 topic pub yaml file input

---

ros2topic/ros2topic/api/__init__.py
ros2topic/ros2topic/verb/bw.py
ros2topic/ros2topic/verb/delay.py
ros2topic/ros2topic/verb/echo.py
ros2topic/ros2topic/verb/hz.py
ros2topic/test/test_bw_delay_hz.py
ros2topic/test/test_cli.py

This PR adds support for QoS configuration for the verbs: bw, delay and hz.
It moves the logic to decide on the QoS from `echo` into `ros2topic.api` to keep the same logic for the 4 verbs.
I'm not really satisfied with my `extract_qos_arguments` function. It's a bit useless, it might be cleaner to just pass the full args to each `_rostopic_verb` function 
Resolves: #719

Add support for topic QOS for ros2topic bw, delay and hz

---

ros2run/ros2run/api/__init__.py

address https://github.com/ros2/ros2cli/issues/895

add signal handler SIGIN/SIGTERM to ros2run.

---

ros2param/ros2param/api/__init__.py
ros2param/test/test_verb_load.py

address https://github.com/ros2/ros2cli/issues/863
depends on https://github.com/ros2/rclpy/pull/1193

fix loading parameter behavior from yaml file.
