- ros2cli/package.xml
- ros2cli/test/test_pep257.py
- ros2node/package.xml
- ros2node/test/test_pep257.py
- ros2pkg/package.xml
- ros2pkg/test/test_pep257.py
- ros2topic/package.xml
- ros2topic/test/test_pep257.py
[![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2741)](http://ci.ros2.org/job/ci_linux/2741/)
> add pep257 tests

- ros2cli/completion/ros2-argcomplete.zsh
- ros2cli/setup.py
It just sources the bash one next to it.
> add argcomplete script for zsh

- ros2topic/ros2topic/api/__init__.py
- ros2topic/ros2topic/verb/list.py
Should fix https://github.com/ros2/ros2cli/issues/8
This feature can be added back when I know how to pass arguments through the xmlrpc bridge to the daemon.
> revert no_demangle option until it can be fixed

- ros2run/ros2run/command/run.py
> Removed node from call to get_executable path in ros2 run command,

- ros2msg/package.xml
- ros2msg/test/test_api.py
- ros2msg/test/test_cli.py
- ros2pkg/test/test_api.py
- ros2pkg/test/test_cli.py
- ros2srv/package.xml
- ros2srv/test/test_api.py
- ros2srv/test/test_cli.py
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2802)](http://ci.ros2.org/job/ci_linux/2802/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=321)](http://ci.ros2.org/job/ci_linux-aarch64/321/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2269)](http://ci.ros2.org/job/ci_osx/2269/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2940)](http://ci.ros2.org/job/ci_windows/2940/)
Ready for review.
> add unit tests

- ros2cli/ros2cli/daemon/__init__.py
- ros2msg/ros2msg/api/__init__.py
- ros2node/ros2node/verb/list.py
- ros2run/ros2run/command/run.py
- ros2service/ros2service/verb/call.py
- ros2srv/ros2srv/api/__init__.py
- ros2topic/package.xml
- ros2topic/ros2topic/verb/pub.py
Beside other changes fixes #17.
> various fixes and improvements

- ros2topic/ros2topic/verb/pub.py
> fix population of recursive message fields

- ros2topic/ros2topic/verb/echo.py
This will allow to print every image message with: `ros2 topic echo /image`
> truncate arrays, bytes, and strings by default, add option to show in full or use custom threshold

- ros2msg/ros2msg/verb/show.py
- ros2service/ros2service/verb/call.py
- ros2srv/ros2srv/verb/show.py
- ros2topic/ros2topic/verb/echo.py
- ros2topic/ros2topic/verb/pub.py
> better error message

- ros2cli/ros2cli/command/daemon.py
- ros2cli/ros2cli/daemon/__init__.py
- ros2cli/ros2cli/node/daemon.py
- ros2cli/ros2cli/verb/daemon/start.py
- ros2cli/ros2cli/verb/daemon/status.py
- ros2cli/ros2cli/verb/daemon/stop.py
- ros2cli/setup.py
> add daemon command with verbs status, start, stop

- ros2cli/ros2cli/command/__init__.py
- ros2cli/ros2cli/node/daemon.py
- ros2cli/ros2cli/node/direct.py
- ros2cli/ros2cli/node/strategy.py
- ros2cli/ros2cli/verb/__init__.py
- ros2cli/ros2cli/verb/daemon/__init__.py
- ros2msg/ros2msg/api/__init__.py
- ros2msg/ros2msg/verb/__init__.py
- ros2node/ros2node/api/__init__.py
- ros2node/ros2node/verb/__init__.py
- ros2pkg/ros2pkg/verb/__init__.py
- ros2run/ros2run/api/__init__.py
- ros2service/ros2service/api/__init__.py
- ros2service/ros2service/verb/__init__.py
- ros2srv/ros2srv/api/__init__.py
- ros2srv/ros2srv/verb/__init__.py
- ros2topic/ros2topic/api/__init__.py
- ros2topic/ros2topic/verb/__init__.py
> implicitly inherit from object

- ros2topic/package.xml
- ros2topic/test/test_primitives.py
Connects to ros2/system_tests#191
> use test_msgs

- ros2run/ros2run/api/__init__.py
> invoke Python scripts on Windows with interpreter

- ros2service/package.xml
- ros2service/ros2service/verb/call.py
- ros2topic/ros2topic/api/__init__.py
- ros2topic/ros2topic/verb/pub.py
This moves the logic for filling messages from ros2topic pub verb to ros2topic api and use it to fill request messages. @dirk-thomas to confimr that's the right place to move it to
> Fix request message population

- ros2service/ros2service/verb/call.py
> wait for service before calling it

- ros2service/package.xml
- ros2service/ros2service/api/__init__.py
- ros2service/ros2service/verb/call.py
- ros2topic/package.xml
- ros2topic/ros2topic/api/__init__.py
- ros2topic/ros2topic/verb/pub.py
> add type completer for 'topic pub' and 'service call'

- ros2cli/ros2cli/node/daemon.py
- ros2cli/ros2cli/verb/daemon/start.py
> 'daemon start' waits until it has been started before returning

- ros2cli/setup.py
- ros2msg/setup.py
- ros2node/setup.py
- ros2pkg/setup.py
- ros2run/setup.py
- ros2service/setup.py
- ros2srv/setup.py
- ros2topic/setup.py
Connects to ament/ament_index#29.
> set zip_safe to avoid warning during installation

- ros2node/ros2node/api/__init__.py
> ignore empty or None node names

- ros2topic/ros2topic/verb/info.py
- ros2topic/setup.py
- ros2topic/test/test_info.py
Counts publishers and subscribers.  The second part of #60.
Connects to #60
> Info verb for ros2topic

- ros2pkg/package.xml
follow up PR from https://github.com/ros2/ros2cli/pull/42#issuecomment-385086830
> add ament_package

- ros2cli/ros2cli/entry_points.py
- ros2cli/ros2cli/plugin_system.py
- ros2service/ros2service/verb/call.py
- ros2topic/ros2topic/verb/pub.py
> ignore F841 from latest Pyflakes release

- ros2cli/colcon.pkg
> add colcon.pkg file to source completion scripts

- ros2lifecycle/package.xml
- ros2lifecycle/ros2lifecycle/verb/set.py
> ros2lifecycle: fix dep and import

- ros2pkg/ros2pkg/verb/create.py
Fixes #109.
I didn't run CI for this but ran the package tests as well as the actual verb locally.
> ros2pkg: avoid requiring git

- ros2cli/ros2cli/node/daemon.py
Fixes #108.
I didn't run CI for this but ran the package tests locally as well as the actual verb on a Windows machine.
> hide window of spawned daemon

- ros2cli/package.xml
- ros2cli/ros2cli/daemon/__init__.py
- ros2cli/ros2cli/node/daemon.py
- ros2cli/setup.py
- ros2lifecycle/package.xml
- ros2lifecycle/setup.py
- ros2msg/package.xml
- ros2msg/setup.py
- ros2node/package.xml
- ros2node/setup.py
- ros2param/package.xml
- ros2param/setup.py
- ros2pkg/package.xml
- ros2pkg/setup.py
- ros2run/package.xml
- ros2run/setup.py
- ros2service/package.xml
- ros2service/setup.py
- ros2srv/package.xml
- ros2srv/setup.py
- ros2topic/package.xml
- ros2topic/ros2topic/verb/pub.py
- ros2topic/setup.py
Opening for visibility, this will be fast forwarded on the bouncy branch.
This brings 2 PRs to the bouncy branch:
https://github.com/ros2/ros2cli/pull/121
https://github.com/ros2/ros2cli/pull/123
> Bouncy patch1: fast-forward to master

- ros2lifecycle/package.xml
- ros2param/package.xml
Noticed this when reviewing another PR.
I think this was a copy-paste from other packages actually using yaml.
Requesting review from @dirk-thomas that implemented these 2 verbs
> remove apparently unused yaml dependency

- ros2cli/package.xml
- ros2cli/setup.py
- ros2lifecycle/package.xml
- ros2lifecycle/setup.py
- ros2msg/package.xml
- ros2msg/setup.py
- ros2node/package.xml
- ros2node/setup.py
- ros2param/package.xml
- ros2param/ros2param/verb/list.py
- ros2param/setup.py
- ros2pkg/package.xml
- ros2pkg/setup.py
- ros2run/package.xml
- ros2run/setup.py
- ros2service/package.xml
- ros2service/setup.py
- ros2srv/package.xml
- ros2srv/setup.py
- ros2topic/package.xml
- ros2topic/ros2topic/verb/echo.py
- ros2topic/setup.py
- ros2topic/test/test_echo.py
> Fast forward Bouncy branch to current master for Bouncy patch 2 release

- ros2topic/package.xml
- ros2topic/ros2topic/verb/delay.py
- ros2topic/setup.py
Porting rostopic delay command from ROS to ROS2. Display delay of topic from timestamp in header.
Usage: ros2 topic delay /topic_name
Signed-off-by: Chris Ye <chris.ye@intel.com>
Connects to: #132
> Enable ros2topic delay command

- ros2lifecycle/ros2lifecycle/api/__init__.py
- ros2lifecycle/ros2lifecycle/verb/list.py
- ros2lifecycle/ros2lifecycle/verb/nodes.py
- ros2lifecycle/ros2lifecycle/verb/set.py
- ros2lifecycle/setup.py
> Lifecycle refactor

- ros2lifecycle/ros2lifecycle/verb/get.py
> fix ros2 lifecycle get

- ros2msg/test/test_api.py
- ros2pkg/test/test_api.py
- ros2srv/test/test_api.py
> use collections.abc.Iterable

- ros2lifecycle/ros2lifecycle/verb/get.py
- ros2lifecycle/ros2lifecycle/verb/set.py
- ros2node/ros2node/api/__init__.py
- ros2param/ros2param/verb/delete.py
- ros2param/ros2param/verb/get.py
- ros2param/ros2param/verb/list.py
- ros2param/ros2param/verb/set.py
same fix as for get: https://github.com/ros2/ros2cli/pull/174
> add slash for node name

- ros2node/ros2node/api/__init__.py
- ros2node/ros2node/verb/info.py
- ros2node/setup.py
> add completer for node info <node-name>

- ros2topic/ros2topic/verb/list.py
> duplicate --include-hidden-topics in list verb

- ros2multicast/setup.cfg
to match https://github.com/ros2/ros2cli/blob/66efd10c61bd54ebdff0035102b9878a2acf5b4b/ros2multicast/package.xml#L5
> fixup ros2multicast version

- ros2lifecycle/ros2lifecycle/api/__init__.py
Fixes #169
Edit:
Also Fixes #172
> ros2lifecycle `nodes` and `get` verbs, now showing hidden nodes when requested

- ros2topic/package.xml
- ros2topic/ros2topic/verb/echo.py
Connect to ros2/rosidl_python#35.
> support array.array and numpy.ndarray field types

- ros2service/ros2service/verb/call.py
- ros2topic/ros2topic/verb/pub.py
Similar to colcon/colcon-metadata#14
> use yaml.safe_load instead of deprecated yaml.load

- ros2action/ros2action/verb/send_goal.py
- ros2param/ros2param/api/__init__.py
Follow-up of #212 for uses of `yaml.load` introduced since
> use yaml.safe_load (round2)

- ros2topic/ros2topic/verb/bw.py
- ros2topic/ros2topic/verb/delay.py
- ros2topic/ros2topic/verb/echo.py
- ros2topic/ros2topic/verb/hz.py
- ros2topic/ros2topic/verb/pub.py
Connects to https://github.com/ros2/rclpy/issues/342
> Fix deprecation warnings

- ros2topic/ros2topic/api/__init__.py
- ros2topic/ros2topic/verb/pub.py
- ros2topic/test/qos_subscription.py
Add functionality to `ros2 topic pub` that will allow for QoS parameters to be passed in on the command line.
Partially addresses #156 
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> [ros2topic] Update pub to use qos command line settings.

- ros2component/ros2component/api/__init__.py
> fix service names to contain 'srv' namespace part

- ros2cli/ros2cli/daemon/__init__.py
- ros2cli/ros2cli/node/direct.py
> don't start parameter service in daemon

- ros2cli/ros2cli/node/direct.py
> update help of --spin-time

- ros2action/ros2action/api/__init__.py
- ros2action/ros2action/verb/show.py
- ros2msg/ros2msg/api/__init__.py
- ros2msg/ros2msg/verb/list.py
- ros2msg/ros2msg/verb/show.py
- ros2srv/ros2srv/api/__init__.py
- ros2srv/ros2srv/verb/list.py
- ros2srv/ros2srv/verb/show.py
> use three-part interface names in msg/srv/action show and msg/srv/ list

- ros2pkg/ros2pkg/verb/create.py
> abort pkg create if destination directory exists

- ros2msg/ros2msg/verb/package.py
- ros2srv/ros2srv/verb/package.py
> fix message/service naming in package verbs

- ros2action/ros2action/verb/send_goal.py
Similar to the changes made in #247 and #259.
> [ros2action] Support multiple part action type names for 'send_goal' verb

- ros2param/package.xml
- ros2param/ros2param/verb/list.py
> fix param list for nodes which don't have the service

- ros2param/ros2param/verb/list.py
> fix param list for hidden nodes

- ros2topic/ros2topic/verb/type.py
> Print all topic types

- ros2multicast/ros2multicast/api/__init__.py
- ros2multicast/ros2multicast/verb/send.py
> add --ttl option to multicast send

- ros2interface/ros2interface/api/__init__.py
- ros2interface/ros2interface/verb/list.py
* Add missing indentation to list verb output
* Format show verb error message
> [ros2interface] Fix output formatting

- ros2topic/ros2topic/verb/echo.py
Resolves #136, depends on https://github.com/ros2/rosidl_python/pull/38
Signed-off-by: vinnamkim <vinnam.kim@gmail.com>
> Add no_str and no_arr options for ros2 topic echo

- ros2interface/ros2interface/api/__init__.py
- ros2interface/ros2interface/verb/list.py
- ros2interface/ros2interface/verb/package.py
- ros2interface/ros2interface/verb/show.py
- ros2interface/setup.py
- ros2interface/test/test_api.py
Addressing comments: https://github.com/ros2/ros2cli/pull/288#discussion_r308473106
> ros2interface fixes/changes

- ros2action/ros2action/verb/send_goal.py
- ros2topic/ros2topic/verb/echo.py
Addresses https://github.com/ros2/ros2cli/pull/216/files#r306587997
> Pass keyword arguments by name

- ros2doctor/README.md
Explains purpose and usage of ros2doctor command line tool, and how to add custom checks and report items.
> add ros2doctor README

- ros2component/ros2component/api/__init__.py
Precisely what the title says.
Connected to https://github.com/ros2/rcl/pull/491.
> Use of -r/--remap flags where appropriate.

- ros2doctor/README.md
Updated entry point examples to match the new change in code.
> Update ros2doctor README entry point examples

- ros2action/setup.py
- ros2cli/setup.py
- ros2component/setup.py
- ros2doctor/setup.py
- ros2interface/setup.py
- ros2lifecycle/setup.py
- ros2msg/setup.py
- ros2multicast/setup.cfg
- ros2node/setup.py
- ros2param/setup.py
- ros2pkg/setup.py
- ros2run/setup.py
- ros2service/setup.py
- ros2srv/setup.py
- ros2topic/setup.py
> install package manifest

- ros2action/setup.py
- ros2cli/setup.py
- ros2component/setup.py
- ros2lifecycle/setup.py
- ros2msg/setup.py
- ros2node/setup.py
- ros2param/setup.py
- ros2pkg/setup.py
- ros2run/setup.py
- ros2service/setup.py
- ros2srv/setup.py
- ros2topic/setup.py
Versions now match latest tag and package.xml.
> Update setup.py version

- ros2doctor/ros2doctor/api/rmw.py
- ros2doctor/setup.py
> Add RMW name to report 

- ros2action/setup.py
- ros2component/setup.py
- ros2doctor/setup.py
- ros2interface/setup.py
- ros2lifecycle/setup.py
- ros2msg/setup.py
- ros2multicast/setup.cfg
- ros2node/setup.py
- ros2param/setup.py
- ros2pkg/setup.py
- ros2run/setup.py
- ros2service/setup.py
- ros2srv/setup.py
- ros2topic/setup.py
Related to colcon/colcon-ros#82.
> install resource marker file for packages

- ros2doctor/README.md
> add new args to README

- ros2action/setup.py
- ros2cli/setup.py
- ros2component/setup.py
- ros2lifecycle/setup.py
- ros2msg/setup.py
- ros2multicast/setup.cfg
- ros2node/setup.py
- ros2param/setup.py
- ros2pkg/setup.py
- ros2run/setup.py
- ros2service/setup.py
- ros2srv/setup.py
- ros2topic/setup.py
> [backport dashing] install package manifest

- ros2action/setup.py
- ros2component/setup.py
- ros2lifecycle/setup.py
- ros2msg/setup.py
- ros2multicast/setup.cfg
- ros2node/setup.py
- ros2param/setup.py
- ros2pkg/setup.py
- ros2run/setup.py
- ros2service/setup.py
- ros2srv/setup.py
- ros2topic/setup.py
> [backport dashing] install resource marker file for packages

- ros2action/ros2action/verb/show.py
- ros2interface/ros2interface/verb/show.py
- ros2msg/ros2msg/verb/show.py
- ros2srv/ros2srv/verb/show.py
> ensure ros2 interface show has trailing newline

- ros2doctor/ros2doctor/api/network.py
Check for case when there is no `flags` key in network interfaces.
> Fix NetworkCheck AttributeError

- ros2doctor/ros2doctor/api/rmw.py
Update middleware headline to capital letters for consistency.
> update headline to capital letters

- ros2lifecycle/ros2lifecycle/verb/get.py
- ros2lifecycle/ros2lifecycle/verb/list.py
- ros2lifecycle/ros2lifecycle/verb/nodes.py
- ros2lifecycle/ros2lifecycle/verb/set.py
Precisely what the title says. Small issues / implementation details I came across while working on #391. We'll get full test coverage once that PR's in.
> [ros2lifecycle] Misc fixes

- ros2node/ros2node/api/__init__.py
- ros2node/ros2node/verb/info.py
> [dashing backport] add service clients to ros2node info

- ros2action/ros2action/verb/send_goal.py
Resolve a TODO and use a function from rosidl_runtime_py to get the action interface.
Connects to https://github.com/ros2/ros2cli/issues/218
> [ros2action] Refactor send_goal implementation

- ros2topic/test/qos_subscription.py
Contributes to closing ros2/build_cop#255
> Use imperative mood in constructor docstring.

- ros2interface/ros2interface/command/interface.py
Addressing comment https://github.com/ros2/ros2cli/pull/288#discussion_r368087386
> Add docblock for ros2interface command

- ros2interface/ros2interface/command/interface.py
> [eloquent backport] Add docblock for ros2interface command (#434)

- ros2cli/ros2cli/command/__init__.py
> pass argv to CommandExtension.add_arguments if available

- ros2action/ros2action/verb/info.py
- ros2action/ros2action/verb/list.py
- ros2cli/ros2cli/cli.py
- ros2cli/ros2cli/command/__init__.py
- ros2cli/ros2cli/entry_points.py
- ros2cli/ros2cli/plugin_system.py
- ros2cli/ros2cli/verb/__init__.py
- ros2lifecycle/ros2lifecycle/api/__init__.py
- ros2lifecycle/ros2lifecycle/verb/get.py
- ros2lifecycle/ros2lifecycle/verb/list.py
- ros2lifecycle/ros2lifecycle/verb/set.py
- ros2multicast/ros2multicast/verb/receive.py
- ros2param/ros2param/api/__init__.py
- ros2param/ros2param/verb/dump.py
- ros2param/ros2param/verb/get.py
- ros2param/ros2param/verb/list.py
- ros2pkg/ros2pkg/verb/executables.py
- ros2run/ros2run/command/run.py
- ros2service/ros2service/verb/list.py
- ros2topic/ros2topic/verb/list.py
CI builds in ament/ament_package#112.
> use f-string

- ros2pkg/ros2pkg/verb/create.py
More context at https://github.com/ros2/ros2cli/pull/439#issuecomment-578319122
> [dashing] Backport of 428 'fix create_pkg dependencies for python'

- ros2doctor/ros2doctor/api/package.py
Otherwise, we get a KeyError and get warnings about not being able to find versions for certain packages.
> [ros2doctor] Handle non-metapackages in rosdistro check

- ros2pkg/ros2pkg/resource/ament_cmake/CMakeLists.txt.em
Related to ament/ament_cmake#237.
> use ament_export_targets()

- ros2node/test/test_cli_duplicate_node_names.py
> Remove uses of deprecated ready_fn.

- ros2cli/ros2cli/daemon/__init__.py
Precisely what the title says, as of `flake8` 3.8.
> Fix new flake8 errors.

- ros2topic/ros2topic/verb/echo.py
- ros2topic/test/test_cli.py
Fixes #519
---
I'd like to add a regression test before merging.
> Guard against passing None to rclpy subscriber

- ros2interface/ros2interface/verb/show.py
- ros2interface/test/test_cli.py
> [ros2interface] show "expanded" message definition

- ros2topic/ros2topic/api/__init__.py
- ros2topic/ros2topic/verb/echo.py
- ros2topic/ros2topic/verb/pub.py
- ros2topic/test/test_qos_conversions.py
close https://github.com/ros2/ros2cli/issues/523
Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>
> support QoS Depth and History via ros2 topic pub/echo.

- ros2component/ros2component/api/__init__.py
- ros2component/ros2component/verb/list.py
With no deprecation notices nor warnings.
> [foxy backport] Ensure consistent timeout in ros2component list. (#526)

- ros2cli/package.xml
- ros2cli/ros2cli/entry_points.py
- ros2cli/ros2cli/plugin_system.py
- ros2doctor/package.xml
- ros2doctor/ros2doctor/api/__init__.py
- ros2pkg/ros2pkg/api/create.py
As described in a lot more detail in https://github.com/ros2/ros2/issues/919 , this is a pull request to remove the use of pkg_resources from the ros2cli package.  There are 3 commits here:
* The first commit removes the use of pkg_resources from the ros2cli core code.
* The second one removes it from ros2doctor.
* The third one removes it from ros2pkg.  This one is a little weird, so please see the commit message for a lot of explanation on why I had to do it the way I did.
On Windows, macOS, and Ubuntu before Focal, this will now need `importlib-metadata` installed from pip (done in https://github.com/ros2/ci/pull/482).  Instructions for Rolling were updated in https://github.com/ros2/ros2_documentation/pull/788
> Remove use of pkg_resources

- ros2topic/ros2topic/verb/echo.py
- ros2topic/test/test_echo_pub.py
Complements https://github.com/ros2/rmw/issues/226.
> Add option to ros2 topic echo to report lost messages

- ros2pkg/ros2pkg/resource/ament_cmake/CMakeLists.txt.em
> fix incorrect EXPORT for executables

- ros2pkg/ros2pkg/resource/ament_cmake/CMakeLists.txt.em
> [backport foxy] fix incorrect EXPORT for executables

- ros2pkg/ros2pkg/resource/ament_cmake/CMakeLists.txt.em
> [Dashing] Fix incorrect EXPORT for executables.

- ros2topic/ros2topic/verb/echo.py
- ros2topic/test/test_echo_pub.py
I found this feature useful when doing some debugging.
~~Depends on https://github.com/ros2/rosidl_runtime_py/pull/10~~
> [ros2topic] Add option to echo serialized messages

- ros2service/ros2service/verb/call.py
Fixes ros2/rclpy#608.
If this passes the PR build I don't plan to run CI builds on ci.ros2.org since they won't test the effect of this patch.
> check that passed type is actually a service

- ros2topic/test/test_echo_pub.py
This goes along with https://github.com/ros2/rclpy/pull/621 .  See that PR for CI as well.
> Fix the test in here to use the topic name.

- ros2action/package.xml
- ros2cli/package.xml
- ros2cli_test_interfaces/package.xml
- ros2component/package.xml
- ros2doctor/package.xml
- ros2interface/package.xml
- ros2lifecycle/package.xml
- ros2lifecycle_test_fixtures/package.xml
- ros2multicast/package.xml
- ros2node/package.xml
- ros2param/package.xml
- ros2pkg/package.xml
- ros2run/package.xml
- ros2service/package.xml
- ros2topic/package.xml
I've added myself as a maintainer in all of the `package.xml`s.
> Add Audrow as a maintainer

- ros2cli/ros2cli/node/direct.py
- ros2cli/test/test_direct.py
- ros2topic/ros2topic/verb/bw.py
- ros2topic/ros2topic/verb/delay.py
address https://github.com/ros2/ros2cli/issues/515
> add option to support use_sim_time.

- ros2action/package.xml
- ros2cli/package.xml
- ros2cli_test_interfaces/package.xml
- ros2component/package.xml
- ros2doctor/package.xml
- ros2interface/package.xml
- ros2lifecycle/package.xml
- ros2lifecycle_test_fixtures/package.xml
- ros2multicast/package.xml
- ros2node/package.xml
- ros2param/package.xml
- ros2pkg/package.xml
- ros2run/package.xml
- ros2service/package.xml
- ros2topic/package.xml
Signed-off-by: claireyywang <22240514+claireyywang@users.noreply.github.com>
> remove maintainer

- ros2cli/ros2cli/command/__init__.py
address https://github.com/ros2/ros2cli/issues/607 (backport of https://github.com/ros2/ros2cli/pull/570)
Signed-off-by: Daisuke Sato <daisukes@cmu.edu>
> [foxy] bugfix for #563 (#570)

- ros2pkg/ros2pkg/verb/create.py
> Add space for "ROS 2".

- ros2lifecycle_test_fixtures/CMakeLists.txt
Part of ros2/rclcpp#1613, https://github.com/ros-visualization/rqt/pull/246, and ament/googletest#15.
> Depend on rclcpp::rclcpp target

- ros2topic/ros2topic/verb/echo.py
Signed-off-by: Gonzalo de Pedro <gonzalo@depedro.com.ar>
> Make Lost Messages option ON by default

- ros2param/ros2param/verb/list.py
Fix https://github.com/ros2/ros2cli/issues/645
> Handle None Result #645

- ros2run/ros2run/api/__init__.py
address https://github.com/ros2/ros2cli/issues/601
> check subprocess.returncode to print error message.

- ros2cli/ros2cli/daemon/__init__.py
address https://github.com/ros2/ros2cli/issues/640
> add uuid to ros2 daemon node name.

- ros2cli/ros2cli/cli.py
- ros2param/test/test_verb_dump.py
https://github.com/ros2/ros2cli/commit/5eda5f79db2ab145d4553cf3d6fb51624c2339b7 fixes the test regressions
> Reapply #659

- ros2topic/ros2topic/verb/echo.py
- ros2topic/test/test_echo_pub.py
Based on the ros1 topic echo filtering code, porting this feature over to ros2. Added an all pass and all reject test
> Feature: ros2topic echo filtering with python expression

- ros2action/package.xml
- ros2cli/package.xml
- ros2cli_test_interfaces/package.xml
- ros2component/package.xml
- ros2doctor/package.xml
- ros2interface/package.xml
- ros2lifecycle/package.xml
- ros2lifecycle_test_fixtures/package.xml
- ros2multicast/package.xml
- ros2node/package.xml
- ros2param/package.xml
- ros2pkg/package.xml
- ros2run/package.xml
- ros2service/package.xml
- ros2topic/package.xml
Signed-off-by: Aditya Pande <aditya050995@gmail.com>
> Updated package maintainers

- ros2topic/test/test_echo_pub.py
Goes along with https://github.com/ros2/rmw_fastrtps/pull/583
> Fix special case for fastrtps incompatible QoS.

- ros2topic/ros2topic/verb/echo.py
- ros2topic/test/test_echo_pub.py
address https://github.com/ros2/ros2cli/issues/529
Co-authored-by: Craig Hickman <craig.hickman@ukaea.uk>
> support ros2topic echo once option.

- ros2cli/ros2cli/xmlrpc/local_server.py
address https://github.com/ros2/ros2cli/issues/702
> XMLRPC server accepts request from all local IP addresses.

- ros2component/ros2component/verb/load.py
> Fix the component load help to mention load, not unload.

- ros2topic/ros2topic/verb/pub.py
- ros2topic/test/test_pub.py
> [humble] Backport. Expand auto to the current time when passed to a Header field

- ros2topic/ros2topic/verb/delay.py
- ros2topic/ros2topic/verb/hz.py
@clalancette just typo fix, i think we do not even run CI on this.
> a couple of typo fixes.

- ros2cli/ros2cli/node/network_aware.py
Fixes https://github.com/ros2/ros2cli/issues/736.
https://github.com/ros2/ros2cli/commit/1195df07b48b048fee255ea83160c43275b785be fixes an issue introduced in https://github.com/ros2/ros2cli/pull/652. See https://github.com/ros2/ros2cli/issues/736#issuecomment-1200673304.
https://github.com/ros2/ros2cli/commit/77c5f6c20f1f35881505db5f9d553a71646a6e5f corrects how netifaces is being used (improves the checking it's being done).
> Fix network aware node issue

- ros2cli/ros2cli/node/daemon.py
- ros2cli/ros2cli/node/strategy.py
- ros2cli/test/test_daemon.py
- ros2cli/test/test_strategy.py
address part of https://github.com/ros2/ros2cli/issues/795, significant performance improvement for ros2 daemon.
> Save method list via connection check to XMLRPC server.

- ros2pkg/ros2pkg/resource/ament_python/setup.py.em
> Resolve #790

- ros2param/ros2param/verb/dump.py
- ros2param/test/test_verb_dump.py
- ros2topic/ros2topic/verb/echo.py
just removing options which have been deprecated for humble.
> remove deprecated options

- ros2pkg/ros2pkg/resource/ament_cmake/CMakeLists.txt.em
That is, add the additional PROJECT_NAME into the include path, like we've done since Humble.
> Update the package template for our new include directories.

- ros2cli/ros2cli/cli.py
address https://github.com/ros2/rclpy/issues/1166
> catch ExternalShutdownException ros2cli main.

- ros2doctor/ros2doctor/api/package.py
Fixes https://github.com/ros2/ros2cli/issues/806
Maybe backport to humble and iron too.
> (ros2doctor) fix PackageCheck

- ros2component/ros2component/api/__init__.py
- ros2param/ros2param/api/__init__.py
- ros2param/test/test_api.py
address https://github.com/ros2/ros2cli/issues/865
> Warning: get_parameter_value() is deprecated.

- ros2param/ros2param/verb/dump.py
address https://github.com/ros2/ros2/issues/1517
> ros2 param dump should handle empty list as exception.

- ros2action/ros2action/verb/type.py
- ros2action/setup.py
- ros2action/test/test_cli.py
address https://github.com/ros2/ros2cli/issues/891
> support `ros2 action type <action name>`.

- ros2action/ros2action/api/__init__.py
minor patch fix. @clalancette can you merge this?
> call get_action_interfaces() properly.

- ros2action/ros2action/verb/find.py
- ros2action/setup.py
- ros2action/test/test_cli.py
closes https://github.com/ros2/ros2cli/issues/914
> support 'ros2 action find'.

- ros2node/ros2node/verb/info.py
address part of https://github.com/ros2/ros2_documentation/issues/4610
> ros2node requires fully qualified node name.

- ros2action/ros2action/api/__init__.py
- ros2action/test/fixtures/fibonacci_action_server.py
- ros2action/test/test_cli.py
closes https://github.com/ros2/ros2cli/issues/911
> node name print bug fix with ros2 action info.

- ros2param/ros2param/verb/dump.py
closes https://github.com/ros2/ros2cli/issues/930
replaces https://github.com/ros2/ros2cli/pull/931
> cosmetic fixes for ros2param dump command.

- ros2doctor/README.md
- ros2doctor/ros2doctor/api/__init__.py
- ros2doctor/ros2doctor/command/doctor.py
> New flag and code update for its use
